---

python_config: {}

os_family: "{{ ansible_os_family }}"

os_distro: "{{ ansible_lsb.id | d(ansible_distribution) }}"

py2_os_packages_distro:
  Ubuntu:  # TODO: check
    - python2
    - python2-pip
    - python2-virtualenv
  ManjaroLinux:
    - python2
    - python2-pip
    - python2-virtualenv
py3_os_packages_distro:
  Ubuntu:  # TODO: check
    - python3
    - python3-pip
    - python3-virtualenv
  ManjaroLinux:
    - python
    - python-pip
    - python-virtualenv

py2_pip_distro:
  ManjaroLinux: pip2
  Ubuntu: pip
py3_pip_distro:
  ManjaroLinux: pip
  Ubuntu: pip3

...