---

- name: create avatar folder
  become: true
  file:
    path: "/var/lib/AccountsService/icons/"
    owner: root
    group: root
    mode: 0644
    state: directory

- name: copy avatar
  become: true
  copy:
    src: "{{ user.avatar }}"
    dest: "/var/lib/AccountsService/icons/{{ user.name }}"
    owner: root
    group: root
    mode: 0644

- name: set avatar
  become: true
  lineinfile:
    backup:      false
    create:      true
    dest:        "/var/lib/AccountsService/users/{{ user.name }}"
    group:       root
    insertafter: "[User]"
    line:        "Icon=/var/lib/AccountsService/icons/{{ user.name }}"
    regexp:      "^Icon=.*$"
    owner:       root
    state:       present

...