---

- name: set bash coloring
  become: yes
  lineinfile:
    backup: no
    create: yes
    insertafter: EOF
    line: "export PS{{ item[1].ps }}=\"{{ item[1].style[:-1] }}\""
    mode: "0644"
    owner: "{{ user }}"
    path: "{{ item[0] }}"
    regexp: "^export PS{{ item[1].ps }}=.*$"
    state: present
  with_nested:
    - - "{{ user_homes[user] }}/.bashrc"
      - "{{ user_homes[user] }}/.bash_profile"
    - - ps: 1
        style: |
          {{ '\\[\\e[0;' + (colors.names | d(39) | string) + 'm\\]' + '\\u'
           + '\\[\\e[0;' + (colors.misc  | d(39) | string) + 'm\\]' + '@'
           + '\\[\\e[0;' + (colors.names | d(39) | string) + 'm\\]' + '\\h'
           + '\\[\\e[0;' + (colors.misc  | d(39) | string) + 'm\\]' + ':'
           + '\\[\\e[0;' + (colors.names | d(39) | string) + 'm\\]' + '\\W'
           + '\\[\\e[0;' + (colors.misc  | d(39) | string) + 'm\\]' + '\\$'
           + '\\[\\e[0m\\]'
           + ' '
          }}
      - ps: 2
        style: |
          {{ '\\[\\e[0;' + (colors.names | d(39) | string) + 'm\\]' + '\\u'
           + '\\[\\e[0;' + (colors.misc  | d(39) | string) + 'm\\]' + '>'
           + '\\[\\e[0m\\]'
           + ' '
          }}
      - ps: 3
        style: |
          {{ '#'
           + '?'
           + ' '
          }}
      - ps: 4
        style: |
          {{ '\\${0}'
           + '\\${LINENO}'
           + ':'
           + '>'
          }}

...