---

- name: set bookmarks dirs
  become: yes
  file:
    path: "{{ path }}"
    owner: "{{ user }}"
    mode: "0755"
    state: directory
  with_items:
    - "{{ user_homes[user] }}/.config"
    - "{{ user_homes[user] }}/.config/gtk-3.0"
  loop_control:
    loop_var: path

- name: set bookmarks
  become: yes
  lineinfile:
    backup: yes
    create: yes
    insertafter: "{% if not top %}EOF{% else %}{{ omit }}{% endif %}"
    insertbefore: "{% if top %}BOF{% else %}{{ omit }}{% endif %}"
    line: "{% if bm.path.startswith('/') %}file://{% endif %}{{ bm.path }}{% if bm.name is defined %}{{ ' ' + bm.name }}{% endif %}"
    mode: "0600"
    owner: "{{ user }}"
    path: "{{ user_homes[user] }}/.config/gtk-3.0/bookmarks"
    regexp: "^{% if bm.path.startswith('/') %}file://{% endif %}{{ bm.path }}( .*)?$"
  with_items: "{{ bookmarks }}"
  loop_control:
    loop_var: bm

...