---

- assert:
    that:
      - repos is sequence
      - allowed_keys is sequence

- # name:
  become: yes
  include: key.yml
  with_items: "{{ repos
                | default_key('id')
                | mass_table_join(repo_list, 'id')
                | list
               }}"
  loop_control:
    loop_var: repo

- # name:
  become: yes
  include: repo.yml
  with_items: "{{ repos
                | default_key('id')
                | mass_table_join(repo_list, 'id')
                | list
               }}"
  loop_control:
    loop_var: repo
  notify:
    - update apt cache

- when: empty_sources_list
  name: empty source.list
  become: yes
  copy:
    backup: yes
    content: ""
    dest: /etc/apt/sources.list
  notify:
    - update apt cache

- when: force_update_cache
  meta: noop
  changed_when: yes
  notify:
    - update apt cache

- meta: flush_handlers

...