---

- hosts: localhost
  vars_prompt:
    - name: "masu_vnc_pass"
      prompt: "VNC server password for user masu"
  roles:
    - role: _users
      settings:
        - name: "masu"
          groups: "sudo"
          append: yes
          bashrc.d: yes
        - name: "willow"
        - name: "ansible_user"
          groups: "sudo"
          append: yes
          bashrc.d: yes
    - role: _filesystem
      settings:
        - forall:
            - path: "/home/masu"
              mode: "0755"
            - path: "/home/masu/Pictures"
              mode: "0755"
            - path: "/home/masu/Downloads"
              mode: "0755"
            - path: "/home/masu/Downloads/firefox"
            - path: "/home/masu/Downloads/torrent"
              mode: "0755"
            - path: "/home/masu/Downloads/torrent/ncore"
              mode: "0755"
              recursive: yes
            - path: "/home/masu/Downloads/torrent/current"
            - path: "/home/masu/Downloads/torrent/stopped"
            - path: "/home/masu/Downloads/torrent/watch"
            - path: "/home/masu/Downloads/torrent/index"
            - path: "/home/masu/Dropbox"
            - path: "/home/masu/Projects"
          follow: no
          force: yes
          recurse: no
          owner: "masu"
          group: "masu"
          mode: "0700"
          state: directory
        - path: "/home/willow/ncore"
          follow: no
          force: yes
          owner: "willow"
          group: "willow"
          src: "/home/masu/Downloads/torrent/ncore"
          state: link
    - role: _download
      settings:
        - force: yes
          mode: "0755"
          owner: "masu"
          forall:
            - url: "https://dl.dropboxusercontent.com/u/71173308/Profile/background"
              dest: "/home/masu/Pictures/background"
            - url: "https://dl.dropboxusercontent.com/u/71173308/Profile/avatar"
              dest: "/home/masu/Pictures/avatar"
            - url: "https://dl.dropboxusercontent.com/u/71173308/Profile/lock"
              dest: "/home/masu/Pictures/lockscreen"
            - url: "https://dl.dropboxusercontent.com/u/71173308/Profile/login"
              dest: "/usr/share/backgrounds/loginscreen"
              owner: "root"
    - role: _apt
      repos: "{{ repos_ubuntu_all
               + repos_ubuntu_backports_all
               + repos_ubuntu_security_all
               + repos_ubuntu_updates_all
              }}"
      packages:
        - state: absent
          forall:
            - totem
            - totem-common
            - totem-plugins
            - rhythmbox
            - rhythmbox-data
            - rhythmbox-plugins
            - rhythmbox-plugin-zeitgeist
            - transmission
            - transmission-*
    - role: system
    - role: netlimit
      netlimit_users:
        - "masu"
        - "willow"
    - role: server4rdp
    - role: server4ssh
    - role: server4torrent
    - role: server4vm
      docker_users:
        - "masu"
        - "willow"
    - role: server4vnc
      settings:
        - user: "masu"
          password: "{{ masu_vnc_pass }}"
    - role: _vars
      settings:
        - forall:
            - line: "alias dlast=docker\\ ps\\ -l\\ -q"
            - line: "alias pip=pip3.5"
          type: all
    - role: devenv
      umake:
        - category: scala
          framework: scala-lang
        - category: ide
          framework: idea
    - role: devenv4java
    - role: devenv4python
      envs:
        - executable: pip3
          name:
            - tqdm
            - pytz
            - ipython
            - ipywidgets
            - jupyter
            - jupyter-declarativewidgets
            - cython
            - numpy
            - scipy
            - scikit-learn
            - xgboost
            - pandas
            - matplotlib
            - seaborn
            - pymongo
            - pyinstaller
            - py4j
            - thefuck
    - role: _vars
      settings:
        - user: "masu"
          type: all
          forall:
            - line: "alias python=python3.5"
              regexp: "^alias python=.*$"
            - line: "alias pip=python3.5"
              regexp: "^alias pip=.*$"
    - role: desktop
    - role: desktop4browse
    - role: desktop4comm
    - role: desktop4latex
    - role: desktop4media
    - role: desktop4office
    - role: desktop4remote
    - role: desktop4wine
    - role: _gnome
      settings:
        - user: "masu"
          xzap: yes
        - login_background: "/usr/share/backgrounds/loginscreen"
        - user: "masu"
          workspaces_h: 2
          workspaces_v: 2
        - user: "willow"
          workspaces_h: 1
          workspaces_v: 1
        - user: "masu"
          background: "/home/masu/Pictures/background"
          lock_background: "/home/masu/Pictures/lockscreen"
          avatar: "/home/masu/Pictures/avatar"
          show_name: yes
          show_icons: yes
          onclick_minimize: yes
        - user: "masu"
          bookmarks:
            - name: "Dropbox"
              location: "/home/masu/Dropbox"
            - name: "Projects"
              location: "/home/masu/Projects"
            - name: "DL Firefox"
              location: "/home/masu/Downloads/firefox"
            - name: "DL torrent"
              location: "/home/masu/Downloads/torrent"
            - name: "DL ncore"
              location: "/home/masu/Downloads/torrent/ncore"
        - hide_login: yes
          forall:
            user:
              - "ansible_user"
    - role: _apt
      upgrade: yes
      autoremove: yes
    - role: _vars
      settings:
        - user: "masu"
          state: present
          type: all
          backup: no
          forall:
            - line: "{{ 'export PS1=\"'
                        + '\\[\\e[0;1;36m\\]' + '\\u'
                        + '\\[\\e[0;1;33m\\]' + '@'
                        + '\\[\\e[0;1;36m\\]' + '\\h'
                        + '\\[\\e[0;1;33m\\]'+ ':'
                        + '\\[\\e[0;1;36m\\]' + '\\W'
                        + '\\[\\e[0;1;33m\\]' + '\\$'
                        + '\\[\\e[0m\\]'
                        + ' \"' }}"
              regexp: "^export PS1=.*$"
            - line: "{{ 'export PS2=\"'
                        + '\\[\\e[0;1;33m\\]' + '\\$'
                        + '\\[\\e[0;1;33m\\]' + '>'
                        + '\\[\\e[0m\\]'
                        + ' '
                        + '\"' }}"
              regexp: "^export PS2=.*$"
            - line: "alias clear=echo\\ -e\\ '\\e[2J\\n\\n'"
              regexp: "^alias clear=.*$"
