---

- name: "GNOME: Set background"
  when: "{{ username is defined
            and settings.background is defined }}"
  become: yes
  gsettings:
    state: "{{ (settings.background is none) | ternary('absent', 'present') }}"
    user: "{{ username }}"
    schema: "org.gnome.desktop.background"
    key: "picture-uri"
    value: "{{ 'file://'+settings.background }}"

- name: "GNOME: Set login background: disable display of custom backgrounds"
  when: "{{ username is undefined
            and settings.login_background is defined }}"
  become: yes
  gsettings:
    state: "present"
    user: "lightdm"
    schema: "com.canonical.unity-greeter"
    key: "draw-user-backgrounds"
    value: "{{ (settings.login_background is none) | ternary('true', 'false') }}"

- name: "GNOME: Set login background"
  when: "{{ username is undefined
            and settings.login_background is defined }}"
  become: yes
  gsettings:
    state: "{{ (settings.login_background is none) | ternary('absent', 'present') }}"
    user: "lightdm"
    schema: "com.canonical.unity-greeter"
    key: "background"
    value: "{{ settings.login_background }}"

- name: "GNOME: Set lockscreen background: disable display of custom backgrounds"
  when: "{{ username is defined
            and settings.lock_background is defined }}"
  become: yes
  gsettings:
    state: "present"
    user: "{{ username }}"
    schema: "com.canonical.unity-greeter"
    key: "draw-user-backgrounds"
    value: "{{ (settings.lock_background is none) | ternary('true', 'false') }}"

- name: "GNOME: Set lockscreen background"
  when: "{{ username is defined
            and settings.lock_background is defined }}"
  become: yes
  gsettings:
    state: "{{ (settings.lock_background is none) | ternary('absent', 'present') }}"
    user: "{{ username }}"
    schema: "com.canonical.unity-greeter"
    key: "background"
    value: "{{ settings.lock_background }}"

- name: "GNOME: Create bookmark location 1"
  when: "{{ username is defined
            and settings.bookmarks is defined }}"
  become_user: "{{ username }}"
  file:
    mode: "0755"
    owner: "{{ username }}"
    path: "{{ username | user_home }}/.config"
    state: directory

- name: "GNOME: Create bookmark location 2"
  when: "{{ username is defined
            and settings.bookmarks is defined }}"
  become: yes
  become_user: "{{ username }}"
  file:
    mode: "0755"
    owner: "{{ username }}"
    path: "{{ username | user_home }}/.config/gtk-3.0"
    state: directory

- name: "GNOME: Set location bookmarks"
  when: "{{ username is defined
            and settings.bookmarks is defined }}"
  become: yes
  become_user: "{{ username }}"
  lineinfile:
    backup: yes
    create: yes
    dest: "{{ username | user_home }}/.config/gtk-3.0/bookmarks"
    insertbefore: EOF
    line: "file://{{ __v.location }} {{ __v.name | d('') }}"
    state: "{{ __v.state | d('present') }}"
  with_items: "{{ settings.bookmarks | d([]) }}"
  loop_control:
    loop_var: "__v"

- name: "GNOME: Copy avatar"
  when: "{{ username is defined
            and settings.avatar is defined }}"
  become: yes
  copy:
    backup: no
    dest: "/var/lib/AccountsService/icons/{{username}}"
    follow: yes
    force: yes
    group: "{{ root_user }}"
    mode: "0644"
    owner: "{{ root_user }}"
    src: "{{ settings.avatar }}"

- name: "GNOME: Set avatar"
  when: "{{ username is defined
            and settings.avatar is defined }}"
  become: yes
  lineinfile:
    backup: yes
    dest: "/var/lib/AccountsService/users/{{username}}"
    line: "{{ (settings.avatar is none) |
              ternary('Icon=', 'Icon=/var/lib/AccountsService/icons/'+username) }}"
    regexp: "^Icon=.*$"
    state: present

- name: "GNOME: Set workspaces (horizontal)"
  when: "{{ username is defined
            and settings.workspaces_h is defined }}"
  become: yes
  gsettings:
    state: "{{ (settings.workspaces_h is none) | ternary('absent', 'present') }}"
    user: "{{ username }}"
    schema: "org.compiz.core:/org/compiz/profiles/unity/plugins/core/"
    key: "hsize"
    value: "{{ settings.workspaces_h }}"

- name: "GNOME: Set workspaces (vertical)"
  when: "{{ username is defined
            and settings.workspaces_v is defined }}"
  become: yes
  gsettings:
    state: "{{ (settings.workspaces_v is none) | ternary('absent', 'present') }}"
    user: "{{ username }}"
    schema: "org.compiz.core:/org/compiz/profiles/unity/plugins/core/"
    key: "vsize"
    value: "{{ settings.workspaces_v }}"

- name: "GNOME: Show user's name"
  when: "{{ username is defined
            and settings.show_name is defined }}"
  become: yes
  gsettings:
    state: "{{ (settings.show_name is none) | ternary('absent', 'present') }}"
    user: "{{ username }}"
    schema: "com.canonical.indicator.session"
    key: "show-real-name-on-panel"
    value: "{{ settings.show_name }}"

- name: "GNOME: Show desktop icons"
  when: "{{ username is defined
            and settings.desktop_icons is defined }}"
  become: yes
  gsettings:
    state: "{{ (settings.desktop_icons is none) | ternary('absent', 'present') }}"
    user: "{{ username }}"
    schema: "org.gnome.desktop.background"
    key: "show-desktop-icons"
    value: "{{ settings.desktop_icons }}"

- name: "GNOME: Set X-terminate keyboard shortcut"
  when: "{{ settings.xterminate is defined }}"
  include: xterminate.yml
  vars:
    enable: "{{ settings.xterminate }}"