---

- name: "Repositories and packages"
  include: apt.yml
  vars:
    repos: "{{ apt.repos }}"
    packages: "{{ apt.packages }}"
    pip2_packages: "{{ apt.python2_packages }}"
    pip3_packages: "{{ apt.python3_packages }}"
    upgrade: "{{ apt.upgrade | d('yes') }}"
    autoremove: "{{ apt.upgrade | d('yes') }}"

- name: "Create users and generate SSH keys"
  become: yes
  user:
    append: yes
    createhome: yes
    generate_ssh_key: yes
    move_home: yes
    ssh_key_file: .ssh/id_rsa
    state: present
#    password:  # TODO
#    update_password: yes
    comment: "{{ user.comment | d(omit) }}"
    expires: "{{ user.expires | d(omit) }}"
    group:   "{{ user.group   | d(omit) }}"
    groups:  "{{ user.groups  | d(omit) }}"
    home:    "{{ user.home    | d(omit) }}"
    name:    "{{ user.name    | d(omit) }}"
    system:  "{{ user.system  | d(omit) }}"
  with_items: "{{ users }}"
  loop_control:
    loop_var: "user"

- name: "Download common resources"
  when: "{{ online_resources is defined }}"
  become: yes
  include: download.yml
  vars:
    details: "{{ item }}"
  with_items: "{{ online_resources |
                  selectattr('users', 'undefined') |
                  list }}"

- name: "Set up common files and folders"
  when: "{{ filesystem_resources is defined }}"
  become: yes
  include: filesystem.yml
  vars:
    details: "{{ item }}"
  with_items: "{{ filesystem_resources |
                  selectattr('users', 'undefined') |
                  list }}"

- name: "Set common gnome desktop settings"
  include: gnome_desktop.yml
  become: yes
  vars:
    settings: "{{ item }}"
  with_items: "{{ visual_settings |
                  selectattr('users', 'undefined') |
                  list }}"

- name: "Set up users"
  include: users.yml
  vars:
    user: "{{ item }}"
  with_items: "{{ users }}"

- name: "Set no-internet option"
  include: no-internet.yml
  vars:
    add_users: "{{ users |
                   map(attribute='name') |
                   list }}"
