---

- name: "Repositories and packages"
  include: apt.yml
  vars:
    debconfs: "{{ apt.debconfs }}"
    repos: "{{ apt.repos }}"
    packages: "{{ apt.packages }}"
    pip2_packages: "{{ apt.python2_packages | d([]) }}"
    pip3_packages: "{{ apt.python3_packages | d([]) }}"
    upgrade: "{{ apt.upgrade | d('yes') }}"
    autoremove: "{{ apt.upgrade | d('yes') }}"

- name: "Set no-internet option"
  include: no-internet.yml
  vars:
    add_users: "{{ users |
                   map(attribute='name') |
                   list }}"

- name: "Create users and generate SSH keys"
  become: yes
  user:
    append: yes
    createhome: yes
    generate_ssh_key: yes
    move_home: yes
    ssh_key_file: .ssh/id_rsa
    state: "{{ user.state | d('present') }}"
    password: "{{ user.password | d(omit) }}"
    update_password: "{{ user.update_password | d(omit) }}"
    comment: "{{ user.comment | d(omit) }}"
    expires: "{{ user.expires | d(omit) }}"
    group:   "{{ user.group   | d(omit) }}"
    groups:  "{{ user.groups  | d(omit) }}"
    home:    "{{ user.home    | d(omit) }}"
    name:    "{{ user.name    | d(omit) }}"
    system:  "{{ user.system  | d(omit) }}"
  with_items: "{{ users }}"
  loop_control:
    loop_var: "user"

- name: "Download common resources"
  when: "{{ online_resources is defined }}"
  become: yes
  include: download.yml
  vars:
    details: "{{ item }}"
  with_items: "{{ online_resources |
                  selectattr('users', 'undefined') |
                  list }}"

- name: "Set up common files and folders"
  when: "{{ filesystem_resources is defined }}"
  become: yes
  include: filesystem.yml
  vars:
    details: "{{ item }}"
  with_items: "{{ filesystem_resources |
                  selectattr('users', 'undefined') |
                  list }}"

- name: "Set common gnome desktop settings"
  when: "{{ desktop_settings is defined }}"
  include: gnome.yml
  become: yes
  vars:
    settings: "{{ item }}"
  with_items: "{{ desktop_settings |
                  selectattr('users', 'undefined') |
                  list }}"

- name: "Set up users"
  include: users.yml
  vars:
    user: "{{ item }}"
  with_items: "{{ users }}"


- name: "Set up common env"
  become: yes
  lineinfile:
    create: yes
    dest: "/etc/environment"
    line: "{{ env | env_create }}"
    state: "{{ env.state | d('present') }}"
  with_flattened: "{{ desktop_settings |
                      selectattr('env', 'defined') |
                      selectattr('users', 'undefined') |
                      map(attribute='env') |
                      d([]) |
                      list }}"
  loop_control:
    loop_var: "env"
