- name: add repository keys
  become_method: sudo
  become: yes
  apt_key:
    keyserver: "{{ item.keyserver }}"
    state: present
    id: "{{ item.key }}"
  with_items:
    - "{{ repo_ubuntu_desktop }}"
    - "{{ repo_dropbox }}"
- name: add repositories
  become_method: sudo
  become: yes
  apt_repository:
    mode: "{{ priv_sources }}"
    repo: "{{ item }}"
    state: present
    update_cache: false
  with_items:
    - "{{ repo_multiverse1 }}"
    - "{{ repo_multiverse2 }}"
    - "{{ repo_multiverse3 }}"
    - "{{ repo_multiverse4 }}"
    - "{{ repo_canonical }}"
    - "{{ repo_ubuntu_desktop.repo }}"  # key required
    - "{{ repo_dropbox.repo }}"  # key required
- name: update apt cache
  become_method: sudo
  become: yes
  apt:
    update_cache: yes
- name: check if ttf fonts are present
  stat:
    path: /usr/share/fonts/truetype/msttcorefonts/
  register: ttf_files
- name: accept ttf license
  become_method: sudo
  become: yes
  when: not "{{ ttf_files.stat.exists }} == 'false'"
  shell: 'echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections'
- name: install packages
  become_method: sudo
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libfreetype6  # fonts
    - libfreetype6-dev  # fonts
    - libfontconfig  # fonts
    - ttf-mscorefonts-installer  # fonts
    - ttf-ubuntu-font-family  # fonts
    - fonts-ubuntu-font-family-console  # fonts
    - caffeine
    - unity-tweak-tool
    - pinta
    - gimp
    - inkscape
    - ubuntu-restricted-extras  # codecs
    - libavcodec-extra  # codecs
    - ffmpeg  # codec
    - mplayer
    - smplayer
    - youtube-dl
    - lame  # codec
    - clementine
    - virtualbox
    - rdesktop
    - dropbox
#    - nautilus-dropbox
    - unrar
    - deluged
    - deluge-gtk
    - deluge-console
    - deluge-webui
    - skype
    - gtk2-engines-murrine:i386  # Skype visual
    - gtk2-engines-pixbuf:i386  # Skype visual
  ignore_errors: "{{ ansible_check_mode }}"
- name: apt upgrade
  become_method: sudo
  become: yes
  apt: upgrade=yes

