---

- name: "NO-INTERNET: ni127 group"
  become: yes
  group:
    name: ni127
    state: present
    system: yes
- name: "NO-INTERNET: ni192 group"
  become: yes
  group:
    name: ni192
    state: present
    system: yes

- name: "NO-INTERNET: copy iptables rules"
  become: yes
  copy:
    backup: yes
    dest: "/etc/network/if-pre-up.d/"
    follow: yes
    force: no
    mode: "0755"
    owner: "{{ root_user | d('root') }}"
    src: "no-internet/ni_group_rule"

- name: "NO-INTERNET: copy ni127 command"
  become: yes
  copy:
    backup: yes
    dest: "/usr/bin/ni127"
    follow: yes
    force: no
    mode: "0755"
    owner: "{{ root_user | d('root') }}"
    src: "no-internet/ni127.sh"
- name: "NO-INTERNET: copy ni192 command"
  become: yes
  copy:
    backup: yes
    dest: "/usr/bin/ni192"
    follow: yes
    force: no
    mode: "0755"
    owner: "{{ root_user | d('root') }}"
    src: "no-internet/ni192.sh"

- name: "NO-INTERNET: users to groups"
  become: yes
  user:
    name: "{{ item }}"
    groups: "ni127,ni192"
    append: yes
    state: present
  with_items: "{{ add_users }}"

