---

- name: "accept oracle license"
  when: "{{ oracle_java_check_package in packages }}"
  become: yes
  debconf:
    name: 'oracle-java8-installer'
    question: 'shared/accepted-oracle-license-v1-1'
    value: 'true'
    vtype: 'select'

