---

- name: set python env variables
  blockinfile:
    backup: yes
    block: "{{ lookup('file', 'python_profile.sh') }}"
    create: yes
    dest: "{{ansible_env.HOME}}/.bashrc"
    follow: yes
    marker: "# ANSIBLE MANAGED: python profile {mark}"
    mode: "0644"
    state: present

