---

- name: "XTERMINATE: Enable global"
  when: "{{ username is undefined
            and enable }}"
  become: yes
  copy:
    backup: no
    dest: "/etc/X11/xorg.conf.d/"
    follow: yes
    force: no
    mode: "0644"
    owner: "{{ root_user | d('root') }}"
    src: "xterminate/90-zap.conf"

- name: "XTERMINATE: Disable global"
  when: "{{ username is undefined
            and not enable }}"
  become: yes
  file:
    follow: yes
    force: yes
    path: "/etc/X11/xorg.conf.d/90-zap.conf"
    state: absent

- name: "XTERMINATE: Set for a user"
  when: "{{ username is defined
            and enable }}"
  become: yes
  become_user: "{{ username }}"
  blockinfile:
    backup: yes
    block: "setxkbmap -option \"terminate:ctrl_alt_bksp\""
    create: yes
    dest: "{{ ansible_env.HOME }}/.bashrc"
    follow: yes
    insertafter: EOF
    marker: "# ANSIBLE MANAGED: xterminate {mark}"
    state: "{{ enable | ternary('present', 'absent') }}"