---

os_family: "{{ ansible_os_family }}"

os_distro: "{{ ansible_lsb.id | d(ansible_distribution) }}"

sudo: |
  {{
    {
      'ManjaroLinux': 'wheel',
      'Ubuntu': 'sudo',
    }[os_distro]
  }}

...