---

- name: "Create bookmark location 1"
  become: yes
  file:
    mode: "0755"
    owner: "{{ __config.user }}"
    group: "{{ __config.user }}"
    path:  "{{ __config.user | user_home }}/.config"
    state: directory
  with_items: "{{ settings | forall |
                  selectattr('user', 'defined') |
                  selectattr('bookmark', 'defined') |
                  list
               }}"
  loop_control:
    loop_var: "__config"

- name: "Create bookmark location 2"
  become: yes
  file:
    mode: "0755"
    owner: "{{ __config.user }}"
    group: "{{ __config.user }}"
    path:  "{{ __config.user | user_home }}/.config/gtk-3.0"
    state: directory
  with_items: "{{ settings | forall |
                  selectattr('user', 'defined') |
                  selectattr('bookmark', 'defined') |
                  list
               }}"
  loop_control:
    loop_var: "__config"

- name: "Set location bookmarks"
  become: yes
  lineinfile:
    backup: yes
    create: yes
    owner: "{{ __config.user }}"
    group: "{{ __config.group | d(__config.user) }}"
    dest:  "{{ __config.user  | user_home }}/.config/gtk-3.0/bookmarks"
    insertbefore: EOF
    line: "file://{{ __config.location }} {{ __config.name | d('') }}"
    state: "{{ __config.state | d('present') }}"
  with_items: "{{ settings |
                  selectattr('bookmarks', 'defined') |
                  forall(default_attribute='location', group_attribute='bookmarks') |
                  list }}"
  loop_control:
    loop_var: "__config"
