---

- name: "Set xorg.conf.d present"
  when: "{{ settings | forall |
            selectattr('xzap', 'defined') |
            selectattr('xzap', 'equalto', True) |
            selectattr('user', 'undefined') |
            list != [] }}"
  become: yes
  file:
    follow: yes
    force: yes
    path: "/etc/X11/xorg.conf.d/"
    owner: "{{ root_user | d('root') }}"
    group: "{{ root_user | d('root') }}"
    state: directory

- name: "Hotkey for restarting X (global) - Enable"
  become: yes
  copy:
    backup: no
    dest: "/etc/X11/xorg.conf.d/"
    follow: yes
    force: yes
    mode: "0644"
    owner: "{{ root_user | d('root') }}"
    src: "90-zap.conf"
  with_items: "{{ settings | forall |
                  selectattr('xzap', 'defined') |
                  selectattr('xzap', 'equalto', True) |
                  selectattr('user', 'undefined') |
                  list |
                  last }}"
  loop_control:
    loop_var: "__config"

- name: "Hotkey for restarting X (global) - Disable"
  become: yes
  file:
    follow: yes
    force: yes
    path: "/etc/X11/xorg.conf.d/90-zap.conf"
    state: absent
  with_items: "{{ settings | forall |
                  selectattr('xzap', 'defined') |
                  selectattr('xzap', 'equalto', False) |
                  selectattr('user', 'undefined') |
                  list }}"
  loop_control:
    loop_var: "__config"

- name: "Hotkey for restarting X (user)"
  become: yes
  blockinfile:
    backup: yes
    block: "setxkbmap -option \"terminate:ctrl_alt_bksp\""
    create: yes
    dest: "{{ __config.user | user_home }}/.bashrc"
    follow: yes
    insertafter: EOF
    marker: "# ANSIBLE MANAGED: xzap {mark}"
    state: "{{ __config.xzap | ternary('present', 'absent') }}"
  with_items: "{{ settings | forall |
                  selectattr('xzap', 'defined') |
                  selectattr('user', 'defined') |
                  list }}"
  loop_control:
    loop_var: "__config"
