---

- assert:
    that:
      - "( umake is undefined
        or umake is sequence
         )"
    msg: "umake should be undefined or sequence"

- name: "Install umake frameworks"
  umake:
    category:  "{{ fw.category  | d(omit) }}"
    framework: "{{ fw.framework | d(omit) }}"
    state:     "{{ fw.state     | d(omit) }}"
    path:      "{{ fw.path      | d(omit) }}"
  with_items: "{{ umake
                | d([])
                | forall
                | list
               }}"
  loop_control:
    loop_var: "fw"
