---

- assert:
    that:
      - "( ( umake is undefined )
        or ( umake is sequence )
         )"
    msg: "umake should be undefined or sequence"

- assert:
    that:
      - "( ( git_lfs is undefined )
        or ( git_lfs is equalto true )
        or ( git_lfs is equalto false )
         )"
    msg: "git_lfs should be a flag"

- name: "Install git-lfs if not disable"
#  when: "{{ git_lfs | d(true) }}"  # BUG: -
  include_role:
    name: _apt
  vars:
#    repos: "{{ repos_git_lfs }}"  # BUG: -
    repos: "{{ git_lfs | d(true) | in([true, 'yes']) | ternary(repos_git_lfs, []) }}"  # BUG: +
    packages:
#      - git-lfs  # BUG: -
       - "{{ git_lfs | d(true) | in([true, 'yes']) | ternary('git-lfs', 'git') }}"  # BUG: +

- name: "Install umake frameworks"
  umake:
    category:  "{{ fw.category  | d(omit) }}"
    framework: "{{ fw.framework | d(omit) }}"
    state:     "{{ fw.state     | d(omit) }}"
    path:      "{{ fw.path      | d(omit) }}"
  with_items: "{{ umake
                | d([])
                | forall(default_key=None)
                | list
               }}"
  loop_control:
    loop_var: "fw"
