- include: commons/install/main.yml
- name: install packages
  become_method: sudo
  become: yes
  pip:
    executable: pip3
    name: "{{ item }}"
    state: present
  with_items:
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - matplotlib
    - seaborn
    - jupyter
    - pymongo
- name: set python env variables
  blockinfile:
    backup: yes
    block: "{{ lookup('file', 'python_profile.sh') }}"
    create: yes
    dest: "{{ansible_env.HOME}}/.bashrc"
    follow: yes
    marker: "# ANSIBLE MANAGED: python profile {mark}"
    mode: 0644
    state: present

