---

- assert:
    that:
      - users is sequence

- name: set iptables present
  package:
    name: iptables
    state: present

- name: set netlimit groups
  become: true
  group:
    name: "{{ group }}"
    state: present
    system: true
  loop_control:
    loop_var: group
  loop:
    - netlimit127
    - netlimit192
    - netlimit10

- name: set iptables rules
  become: true
  blockinfile:
    backup: true
    block: |
      -A OUTPUT -d 127.0.0.0/8 -m owner --gid-owner netlimit10 -j ACCEPT
      -A OUTPUT -d 127.0.0.0/8 -m owner --gid-owner netlimit192 -j ACCEPT
      -A OUTPUT -d 127.0.0.0/8 -m owner --gid-owner netlimit127 -j ACCEPT
      -A OUTPUT -d 10.0.0.0/8 -m owner --gid-owner netlimit10 -j ACCEPT
      -A OUTPUT -d 192.168.0.0/16 -m owner --gid-owner netlimit192 -j ACCEPT
      -A OUTPUT -m owner --gid-owner netlimit10 -j REJECT --reject-with icmp-port-unreachable
      -A OUTPUT -m owner --gid-owner netlimit192 -j REJECT --reject-with icmp-port-unreachable
      -A OUTPUT -m owner --gid-owner netlimit127 -j REJECT --reject-with icmp-port-unreachable
    create: true
    insertafter: "\\*filter"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: NETLIMIT"
    path: /etc/iptables/iptables.rules
    state: present
  notify:
    - restart iptables

- name: set netlimit commands
  become: true
  copy:
    content: |
      #!/bin/bash
      sg netlimit{{ group | d(127, True) }} "$1"
    backup: true
    dest:   "/usr/bin/netlimit{{group}}"
    follow: true
    force:  false
    mode:   "0755"
    owner:  root
  with_items:
    - 127
    - 192
    - 10
    - ""
  loop_control:
    loop_var: group

...