---

- assert:
    that:
      - "( debconfs is defined
        or repos    is defined
        or packages is defined
        or ( autoremove | d(false) )
        or ( upgrade    | d(false) )
         )"
    msg:
      - "debconfs, repos or packages should be defined otherwise autoremove or upgrade should be true"

- assert:
    that:
      - "( debconfs is undefined
        or debconfs is sequence
         )"
    msg:
      - "debconfs should be undefined or sequence"

- assert:
    that:
      - "( repos is undefined
        or repos is sequence
         )"
    msg:
      - "packages should be undefined or sequence"

- assert:
    that:
      - "( packages is undefined
        or packages is sequence
         )"
    msg:
      - "packages should be undefined or sequence"

- assert:
    that:
      - "( upgrade is undefined
        or upgrade is sameas false
        or upgrade is sameas true
         )"
    msg:
      - "upgrade should be undefined or boolean"

- assert:
    that:
      - "( autoremove is undefined
        or autoremove is sameas false
        or autoremove is sameas true
         )"
    msg:
      - "autoremove should be undefined or boolean"

- name: "Set debconfs"
  become: yes
  debconf:
    name:     "{{ item.name     }}"
    question: "{{ item.question }}"
    vtype:    "{{ item.vtype    }}"
    value:    "{{ item.value    }}"
  with_items: "{{ debconfs
                | d([])
                | forall
                | list
               }}"

- name: "Set repository keys with keyserver"
  become: yes
  apt_key:
    state:     "{{ item.state | d('present') }}"
    keyserver: "{{ item.keyserver            }}"
    id:        "{{ item.key                  }}"
  with_items: "{{ repos
                | d([])
                | forall(default_key='repo')
                | selectattr('key', 'defined')
                | list
               }}"

- name: "Set repository keys with GPG keys"
  become: yes
  apt_key:
    state: "{{ item.state   | d('present') }}"
    url:   "{{ item.key_url                }}"
  with_items: "{{ repos
                | d([])
                | forall(default_key='repo')
                | selectattr('key_url', 'defined')
                | list
               }}"

- name: "Set repositories"
  become: yes
  apt_repository:
    mode: 644
    repo:  "{{ item.repo            }}"
    state: "{{ item.state | d(omit) }}"
    update_cache: no
  with_items: "{{ repos
                | d([])
                | forall(default_key='repo')
                | list
               }}"

- name: "Update cache"
  when: "{{ repos is defined }}"
  become: yes
  apt:
    update_cache: yes
  ignore_errors: yes

- name: "Packages..."
  become: yes
  apt:
    allow_unauthenticated: "{{ item.allow_unauthenticated | d(omit) }}"
    cache_valid_time:      "{{ item.cache_valid_time      | d(omit) }}"
    deb:                   "{{ item.deb                   | d(omit) }}"
    default_release:       "{{ item.default_release       | d(omit) }}"
    dpkg_options:          "{{ item.dpkg_options          | d(omit) }}"
    force:                 "{{ item.force                 | d(omit) }}"
    install_recommends:    "{{ item.install_recommends    | d(omit) }}"
    name:                  "{{ item.name                  | d(omit) }}"
    purge:                 "{{ item.purge                 | d(omit) }}"
    state:                 "{{ item.state                 | d(omit) }}"
  with_items: "{{ packages
                | d([])
                | forall(default_key='name')
                | list
               }}"

- name: "Upgrade and/or autoremove"
  when: "( (upgrade    | d(false))
        or (autoremove | d(false))
         )"
  become: yes
  apt:
    upgrade:    "{{ upgrade    | d(omit) }}"
    autoremove: "{{ autoremove | d(omit) }}"
