---

- assert:
    that:
      - packages is sequence

- name: package manager present
  become: true
  apt:
    name:
      - apt
      - ca-certificates
      - apt-transport-https+
      - locales
    state: latest

- name: remove packages
  become: true
  apt:
    name: "{{ item.name | d(item) }}"
    state: absent
  loop: "{{ packages_absent }}"

- name: install packages
  become: true
  apt:
    name: "{{ item.name | d(item) }}"
    state: "{{ upgrade | d('latest', 'present') }}"
  loop: "{{ packages }}"

- name: upgrade packages
  when: upgrade
  apt:
    upgrade: true

...