---

- name: set profile folders
  become: yes
  file:
    owner: "{{ user }}"
    group: "{{ user }}"
    mode:  0700
    path:  "{{ user_homes[user] }}/.mozilla/firefox/ansible.{{ profile.name }}"
    state: directory

# TODO: decide whether times.json is needed
#- name: set profile times.json
#  become: yes
#  template:
#    owner: "{{ user }}"
#    group: "{{ user }}"
#    mode:  0700
#    dest:  "{{ user_homes[user] }}/.mozilla/firefox/ansible.{{ profile.name }}/times.json"
#    src:   times.json.jinja2

- when: profile.prefs is defined
  name: set prefs.js
  become: yes
  lineinfile:
    create: yes
    owner:  "{{ user }}"
    group:  "{{ user }}"
    mode:   0700
    path:   "{{ user_homes[user] }}/.mozilla/firefox/ansible.{{ profile.name }}/prefs.js"
    line:   "user_pref(\"{{
               pref.key
             }}\", {%
               if pref.value is string
                 %}\"{{ pref.value }}\"{%
               else
                 %}{{ pref.value }}{%
               endif
             %});"
    regexp: "user_pref.\"{{ pref.key }}\", .*.;"
  with_dict: "{{ profile.prefs }}"
  loop_control:
    loop_var: pref

- when: profile.account_data is defined
  name: check whether signedInUser.json exists
  become: yes
  stat:
    path: &siujson
      "{{ user_homes[user] }}/.mozilla/firefox/ansible.{{ profile.name }}/signedInUser.json"
  register: siujson

- when: profile.account_data is defined and not siujson.stat.exists
  name: set signedInUser.json
  become: yes
  template:
    owner: "{{ user }}"
    group: "{{ user }}"
    mode:  0700
    dest:  *siujson
    src:   signedInUser.json.jinja2

...