---

- assert:
    that:
      - "( ( envs is undefined )
        or ( envs is sequence )
         )"
    msg: "envs should be undefined or sequence"

- name: "Set environments"
  become: yes
  pip:
    chdir:                    "{{ __env.chdir                    | d(omit) }}"
    editable:                 "{{ __env.editable                 | d(omit) }}"
    executable:               "{{ __env.executable               | d(omit) }}"
    extra_args:               "{{ __env.extra_args               | d(omit) }}"
    name:                     "{{ __env.name                     | d(omit) }}"
    requirements:             "{{ __env.requirements             | d(omit) }}"
    state:                    "{{ __env.state                    | d(omit) }}"
    umask:                    "{{ __env.umask                    | d(omit) }}"
    version:                  "{{ __env.version                  | d(omit) }}"
    virtualenv:               "{{ __env.virtualenv               | d(omit) }}"
    virtualenv_command:       "{{ __env.virtualenv_command       | d(omit) }}"
    virtualenv_python:        "{{ __env.virtualenv_python        | d(omit) }}"
    virtualenv_site_packages: "{{ __env.virtualenv_site_packages | d(omit) }}"
  with_items: "{{ envs
                | d([])
               }}"
  loop_control:
    loop_var: "__env"
