---

default_x_user: "{{ ansible_ssh_user }}"

gnome_settings: []

gnome_settings_list:

  # A11Y
#    org.gnome.desktop.a11y
#    org.gnome.desktop.a11y.applications
#    org.gnome.desktop.a11y.keyboard
#    org.gnome.desktop.a11y.magnifier
#    org.gnome.desktop.a11y.mouse

  # Applications
#    org.gnome.desktop.app-folders
#    org.gnome.desktop.app-folders.folder:/

  # Background
  background_show:
    schema: org.gnome.desktop.background
    key: draw-background
    range: type b
  background:
    schema: org.gnome.desktop.background
    key: picture-uri
    range: type s
  background_icons:
    schema: org.gnome.desktop.background
    key: show-desktop-icons
    range: type b

  # Datetime
#    org.gnome.desktop.datetime

  # Default applications
#    org.gnome.desktop.default-applications
#    org.gnome.desktop.default-applications.office
#    org.gnome.desktop.default-applications.office.calendar
#    org.gnome.desktop.default-applications.office.tasks
#    org.gnome.desktop.default-applications.terminal

  # File-sharing
#    org.gnome.desktop.file-sharing

  # Keyboard
  keyboard_layouts:
    schema: org.gnome.desktop.input-sources
    key: sources
    range: type a(ss)
  keyboard_layout:
    schema: org.gnome.desktop.input-sources
    key: current
  keyboard_xkb_options:
    schema: org.gnome.desktop.input-sources
    key: xkb-options

  # Interface
#    org.gnome.desktop.interface

  # Lockdown
#    org.gnome.desktop.lockdown

  # Media
#    org.gnome.desktop.media-handling

  # Notifications
#    org.gnome.desktop.notifications
#    org.gnome.desktop.notifications.application:/

  # Peripherials
#    org.gnome.desktop.peripherals
#    org.gnome.desktop.peripherals.keyboard
#    org.gnome.desktop.peripherals.mouse
#    org.gnome.desktop.peripherals.tablet:/
#    org.gnome.desktop.peripherals.touchpad
#    org.gnome.desktop.peripherals.touchscreen:/
#    org.gnome.desktop.peripherals.trackball

  # Privacy
#    org.gnome.desktop.privacy

  # Screensaver and lockscreen
  lockscreen:
    schema: org.gnome.desktop.screensaver
    key: picture-uri
    type: s

  # Search
#    org.gnome.desktop.search-providers

  # Session
#    org.gnome.desktop.session

  # Sound
  sound_events:
    schema: org.gnome.desktop.sound
    key: event-sounds
    type: b
  sound_feedback:
    schema: org.gnome.desktop.sound
    key: input-feedback-sounds
    type: b
  sound_theme:
    schema: org.gnome.desktop.sound
    key: theme-name
    type: s

  # Thumbnails
#    org.gnome.desktop.thumbnail-cache
#    org.gnome.desktop.thumbnailers

  # Windowmanager
#    org.gnome.desktop.wm.keybindings
#    org.gnome.desktop.wm.preferences

...