---

dependencies:
  - role: _apt
    repos: "{{ repos_ubuntu_main
             + repos_ubuntu_updates_main
             + repos_ubuntu_universe
             + repos_ubuntu_updates_universe
             + repos_ubuntu_multiverse
             + repos_ubuntu_updates_multiverse
            }}"
    packages:
      - rdesktop
      - vinagre
      - synergy
      - openvpn
      - network-manager-openvpn
      - network-manager-openvpn-gnome
