---

- assert:
    that:
      - repo is mapping

- debug: var=repo

- name: set gpg key
  become: yes
  copy:
    content: "{{ repo.gpgkey }}"
    dest: "{{ repo.gpgkey_file | d('/etc/pki/rpm-gpg/RPM-GPG-KEY-' + repo.id) }}"
    mode: "0644"
    owner: root
    group: root

- name: set repo
  become: yes
  yum_repository:
    baseurl: "{{ repo.baseurl }}"
    description: "{{ repo.name }}"
    name: "{{ repo.id }}"
    gpgcheck: yes
    gpgkey: "file://{{ repo.gpgkey_file | d('/etc/pki/rpm-gpg/RPM-GPG-KEY-' + repo.id) }}"
    enabled: "{{ repo.enabled | d(omit) }}"
    file: "{{ repo.file | d(omit) }}"
    repo_gpgcheck: "{{ repo.repo_gpgcheck | d(omit) }}"
    priority: "{{ repo.priority | d(omit) }}"
    includepkgs: "{{ repo.includepkgs | d(omit) }}"

...