---

dependencies:
  - role: _apt
    debconfs: "{{ oraclejdk_debconfs }}"
    repos: "{{ oraclejdk_repos }}"
    packages:
      - oracle-java8-installer
      - ca-certificates
      - "{{ default | d(false) | ternary('oracle-java8-set-default', 'oracle-java8-installer') }}"
