---

- assert:
    that:
      - users is sequence

- # name:
  become: yes
  include_tasks: user.yml
  with_items: "{{ users
                | default_key('name')
                | list
               }}"
  loop_control:
    loop_var: user

...