---

- assert:
    that:
      - "( ( settings is defined )
       and ( settings is sequence )
         )"
    msg: "settings should be defined and sequence"

- name: "Setting up users..."
  become: yes
  user:
    append:           "{{ __user.append           | d(true) }}"
    createhome:       "{{ __user.createhome       | d(true) }}"
    generate_ssh_key: "{{ __user.generate_ssh_key | d(true) }}"
    move_home:        "{{ __user.move_home        | d(true) }}"
    ssh_key_file:     "{{ __user.ssh_key_file     | d('.ssh/id_rsa') }}"
    state:            "{{ __user.state            | d(omit) }}"
    password:         "{{ __user.password         | d(omit) }}"
    update_password:  "{{ __user.update_password  | d(omit) }}"
    comment:          "{{ __user.comment          | d(omit) }}"
    expires:          "{{ __user.expires          | d(omit) }}"
    group:            "{{ __user.group            | d(omit) }}"
    groups:           "{{ __user.groups           | d(omit) }}"
    home:             "{{ __user.home             | d(omit) }}"
    name:             "{{ __user.name             | d(omit) }}"
    system:           "{{ __user.system           | d(omit) }}"
  with_items: "{{ settings }}"
  loop_control:
    loop_var: "__user"

- name: "Set up bashrc.d support (folder)"
  become: yes
  file:
    path:  "{{ __user.name | user_home }}/append-.bashrc.sh"
    mode:  "0755"
    owner: "{{ __user.name }}"
    group: "{{ __user.group | d(__user.name) | d(omit) }}"
    state: directory
  with_items: "{{ settings
                | selectattr('name', 'defined')
                | selectattr('bashrcd', 'defined')
                | selectattr('bashrcd', 'true')
                | list
               }}"
  loop_control:
    loop_var: "__user"

- name: "Set up bashrc.d support (inclusion)"
  become: yes
  blockinfile:
    backup:      yes
    block:       "{{ lookup('file', 'append-.bashrc.sh') }}"
    create:      yes
    dest:        "{{ __user.name | user_home }}/.bashrc"
    follow:      yes
    insertafter: EOF
    owner:       "{{ __user.name }}"
    group:       "{{ __user.group | d(__user.name) | d(omit) }}"
    marker:      "# ANSIBLE MANAGED: .bashrc.d {mark}"
    state:       present
  with_items: "{{ settings
                | selectattr('name', 'defined')
                | selectattr('bashrcd', 'defined')
                | list
               }}"
  loop_control:
    loop_var: "__user"
