---

- assert:
    that:
      - packages is sequence

- name: package manager present
  become: true
  pacman:
    name:
      - yay
      - ca-certificates
    state: latest

- name: remove packages
  become: true
  pacman:
    name: "{{ item.name | d(item) }}"
    state: absent
  loop: "{{ packages_absent }}"

- name: install packages
  aur:
    name: "{{ item.name | d(item) }}"
    aur_only: false
    skip_installed: true
  loop: "{{ packages }}"

- name: upgrade packages
  when: upgrade
  aur:
    upgrade: true

...