---

- assert:
    that:
      - user_name is defined

- when: user_homes is defined and user_name in user_homes
  name: already checked user home
  set_fact:
    last_user_home: "{{ user_homes[user_name] }}"

- when: user_homes is undefined or user_name not in user_homes
  name: not yet checked user home
  block:
    - name: getent
      become: yes
      getent:
        database: passwd
        key: "{{ user_name }}"
        split: ":"

    - name: set fact
      set_fact:
        user_homes: "{{ user_homes | d({}) | combine({user_name: getent_passwd[user_name][4]}) }}"
        last_user_home: "{{ getent_passwd[user_name][4] }}"

...