---

dependencies:
  - role: _apt
    repos: "{{ repos_git_lfs
             + repos_umake
             }}"
    packages:
      - git
      - "{{ git_lfs
          | d(false)
          | ternary('git-lfs', 'git')
         }}"
      - ubuntu-make
      - g++
      - gcc
      - make
      - libc-bin
      - lsb
      - build-essential
