---

- when: repo.gpgkey is defined
  become: true
  name: set repository keys
  apt_key:
    state: "{{ repo.state  | d(omit) }}"
    data:  "{{ repo.gpgkey           }}"
    id:    "{{ repo.key              }}"

- when: repo.gpgkey is undefined and repo.keyserver is defined
  become: true
  name: set repository keys with keyserver
  apt_key:
    state:     "{{ repo.state     | d(omit) }}"
    keyserver: "{{ repo.keyserver           }}"
    id:        "{{ repo.key                 }}"

- when: repo.gpgkey is undefined and repo.keyserver is undefined and repo.key_url is defined
  become: true
  name: set repository keys with key URL
  apt_key:
    state: "{{ repo.state   | d(omit) }}"
    url:   "{{ repo.key_url           }}"
    key:   "{{ repo.key     | d(omit) }}"

...