---

- assert:
    that:
      - repos is sequence

- include_tasks: key.yml
  with_items: |
    {{ repos
     | default_key('id')
     | mass_table_join(repo_list, 'id')
     | list
    }}
  loop_control:
    loop_var: repo

- include_tasks: repos.yml
  with_items: |
    {{ repos
     | default_key('id')
     | mass_table_join(repo_list, 'id')
     | list
    }}
  loop_control:
    loop_var: repo
  notify:
    - update apt cache

...