- name: add repositories
  become_method: sudo
  become: yes
  apt_repository:
    mode: "{{ priv_sources }}"
    repo: "{{ item }}"
    state: present
    update_cache: false
  with_items:
    # REPO canonical partners | flashplugin-installer
    - "{{ repo_canonical }}"
- name: install packages
  become_method: sudo
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - firefox
    - chromium-browser
    - chromium-codecs-ffmpeg
    - flashplugin-installer

