---

- assert:
    that:
      - debconf is mapping

- name: set debconf
  debconf:
    name:     "{{ debconf.name     | d(omit) }}"
    question: "{{ debconf.question | d(omit) }}"
    unseen:   "{{ debconf.unseen   | d(omit) }}"
    value:    "{{ debconf.value    | d(omit) }}"
    vtype:    "{{ debconf.vtype    | d(omit) }}"

...