---

- assert:
    that:
      - packages is sequence

- # name:
  include_tasks: debconf.yml
  with_items: "{{ packages
                | default_key('name')
                | mass_table_join(debconf_list, 'name', collection=true)
                | sum(start=[])
                | list
               }}"
  loop_control:
    loop_var: debconf

- # name:
  include_tasks: apt.yml
  with_items: "{{ packages
                | default_key('name')
                | list
               }}"
  loop_control:
    loop_var: package

...