############
# login_background
# ----------

- name: "Set login background: disable display of custom backgrounds"
  become: yes
  gsettings:
    state:  present
    user:   "lightdm"
    schema: "com.canonical.unity-greeter"
    key:    "draw-user-backgrounds"
    value:  "{{ __config.login_background is none | ternary('true', 'false') }}"
  with_items: "{{ settings
                | selectattr('user', 'undefined')
                | selectattr('login_background', 'defined')
                | list
                }}"
  loop_control:
    loop_var: "__config"

- name: "Set login background"
  become: yes
  gsettings:
    state:  "{{ __config.login_background is none | ternary('absent', 'present') }}"
    user:   "lightdm"
    schema: "com.canonical.unity-greeter"
    key:    "background"
    value:  "{{ __config.login_background }}"
  with_items: "{{ settings
                | selectattr('user', 'undefined')
                | selectattr('login_background', 'defined')
                | list
               }}"
  loop_control:
    loop_var: "__config"

# ----------
# login_background
############

############
# With user specified
############

############
# avatar
# ----------

- name: "Copy avatar"
  become: yes
  copy:
    backup: no
    dest:   "/var/lib/AccountsService/icons/{{__config.user}}"
    follow: yes
    force:  yes
    group:  "{{ root_user | d('root') }}"
    mode:   "0644"
    owner:  "{{ root_user | d('root') }}"
    src:    "{{ __config.avatar }}"
  with_items: "{{ settings
                | selectattr('user', 'defined')
                | selectattr('avatar', 'defined')
                | list
               }}"
  loop_control:
    loop_var: "__config"

- name: "Set avatar"
  become: yes
  lineinfile:
    backup: yes
    create: yes
    dest:   "/var/lib/AccountsService/users/{{__config.user}}"
    line:   "{{ __config.avatar is none
              | ternary('Icon=', 'Icon=/var/lib/AccountsService/icons/'+__config.user)
             }}"
    regexp: "^Icon=.*$"
    state:  present
  with_items: "{{ settings
                | selectattr('user', 'defined')
                | selectattr('avatar', 'defined')
                | list
               }}"
  loop_control:
    loop_var: "__config"

# ----------
# avatar
############

############
# background
# ----------

- name: "Set background"
  become: yes
  gsettings:
    state:  "{{ __config.background is none | ternary('absent', 'present') }}"
    user:   "{{ __config.user }}"
    schema: "org.gnome.desktop.background"
    key:    "picture-uri"
    value:  "file://{{ __config.background | d(omit) }}"
  with_items: "{{ settings
                | selectattr('user', 'defined')
                | selectattr('background', 'defined')
                | list
               }}"
  loop_control:
    loop_var: "__config"

# ----------
# background
############

############
# lock_background
# ----------

- name: "Set lockscreen background: disable display of custom backgrounds"
  become: yes
  gsettings:
    state:  present
    user:   "{{ __config.user }}"
    schema: "com.canonical.unity-greeter"
    key:    "draw-user-backgrounds"
    value:  "{{ __config.lock_background is none | ternary('true', 'false') }}"
  with_items: "{{ settings
                | selectattr('user', 'defined')
                | selectattr('lock_background', 'defined')
                | list
               }}"
  loop_control:
    loop_var: "__config"

- name: "Set lockscreen background"
  become: yes
  gsettings:
    state:  "{{ __config.lock_background is none | ternary('absent', 'present') }}"
    user:   "{{ __config.user }}"
    schema: "com.canonical.unity-greeter"
    key:    "background"
    value:  "{{ __config.lock_background }}"
  with_items: "{{ settings
                | selectattr('user', 'defined')
                | selectattr('lock_background', 'defined')
                | list
               }}"
  loop_control:
    loop_var: "__config"

# ----------
# lock_background
############

############
# onclick_minize
# ----------

- name: "Set on-click minimization"
  become: yes
  gsettings:
    state:  "{{ __config.onclick_minimize is none | ternary('absent', 'present') }}"
    user:   "{{ __config.user }}"
    schema: "org.compiz.unityshell:/org/compiz/profiles/unity/plugins/unityshell/"
    key:    "launcher-minimize-window"
    value:  "{{ __config.onclick_minimize | bool }}"
  with_items: "{{ settings
                | selectattr('user', 'defined')
                | selectattr('onclick_minimize', 'defined')
                | list
               }}"
  loop_control:
    loop_var: "__config"

# ----------
# onclick_minize
############

############
# show_icons
# ----------

- name: "Show/Hide desktop icons"
  become: yes
  gsettings:
    state:  "{{ __config.show_icons is none | ternary('absent', 'present') }}"
    user:   "{{ __config.user }}"
    schema: "org.gnome.desktop.background"
    key:    "show-desktop-icons"
    value:  "{{ __config.show_icons }}"
  with_items: "{{ settings
                | selectattr('user', 'defined')
                | selectattr('show_icons', 'defined')
                | list
               }}"
  loop_control:
    loop_var: "__config"

# ----------
# show_icons
############

############
# show_name
# ----------

- name: "Show/Hide user's name on panel"
  become: yes
  gsettings:
    state:  "{{ __config.show_name is none | ternary('absent', 'present') }}"
    user:   "{{ __config.user }}"
    schema: "com.canonical.indicator.session"
    key:    "show-real-name-on-panel"
    value:  "{{ __config.show_name }}"
  with_items: "{{ settings
                | selectattr('user', 'defined')
                | selectattr('show_name', 'defined')
                | list
               }}"
  loop_control:
    loop_var: "__config"

# ----------
# show_name
############
