---

- name: "Handle empty list"
  when: "{{ docker_users is undefined }}"
  set_fact: docker_users="{{ [] }}"
- name: "Add users to docker group"
  become: yes
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"
  loop_control:
    loop_var: "username"
