---

- assert:
    that:
      - "( settings is defined
       and settings is sequence
         )"
    msg: "settings should be defined and sequence"

- name: "Applying filesystem settings..."
  become: yes
  file:
    follow:  "{{ __fs.follow  | d(omit) }}"
    force:   "{{ __fs.force   | d(omit) }}"
    group:   "{{ __fs.group   | d(omit) }}"
    mode:    "{{ __fs.mode    | d(omit) }}"
    owner:   "{{ __fs.owner   | d(omit) }}"
    path:    "{{ __fs.path    | d(omit) }}"
    recurse: "{{ __fs.recurse | d(omit) }}"
    src:     "{{ __fs.src     | d(omit) }}"
    state:   "{{ __fs.state   | d(omit) }}"
  with_items: "{{ settings
                | forall
                | list
               }}"
  loop_control:
    loop_var: "__fs"
