- name: generate ssh keys
  become_method: sudo
  become: yes
  user:
    append: yes
    generate_ssh_key: yes
    name: "{{ ansible_user_id }}"
    ssh_key_file: .ssh/id_rsa
    state: present
- include: commons/install.yml
- name: enable video-reset
  lineinfile:
    dest: "/home/{{ansible_user_id}}/.bashrc"
    owner: "{{ ansible_user_id }}"
    regexp: '^setxkbmap -option "terminate:ctrl_alt_bksp"$'
    line: 'setxkbmap -option "terminate:ctrl_alt_bksp"'
    state: present
    create: yes
    insertafter: EOF
- name: set up no-internet option
  include: no-internet.yml

