- name: generate ssh keys
  become_method: sudo
  become: yes
  user:
    append: yes
    generate_ssh_key: yes
    name: "{{ ansible_user_id }}"
    ssh_key_file: .ssh/id_rsa
    state: present
- name: profile.d folder present
  file:
    path: "/etc/profile.d"
    state: directory
- name: bashrc.d folder present
  file:
    path: "{{ansible_env.HOME}}/.bashrc.d"
    mode: 0755
    owner: "{{ ansible_user_id }}"
    state: directory
- name: bashrc.d support
  blockinfile:
    backup: yes
    block: "{{ lookup('file', 'bashrc.app') }}"
    create: yes
    dest: "{{ansible_env.HOME}}/.bashrc"
    follow: yes
    marker: "# ANSIBLE MANAGED: .bashrc.d {mark}"
    mode: 0644
    state: present
- include: commons/install/main.yml
- name: enable video-reset
  become_method: sudo
  become: yes
  copy:
    backup: yes
    dest: "/etc/profile.d/"
    follow: yes
    force: no
    mode: 0644
    owner: root
    src: "profile.d/setxkbmap.sh"
- name: set up no-internet option
  include: no-internet.yml

