---

- name: docker group
  become: yes
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
  tags:
    - docker
    - user
    - group
  with_items: "{{ users }}"
  loop_control:
    loop_var: user

- name: dl command
  become: yes
  copy:
    content: !unsafe |
      #!/bin/bash

      docker ps -l -q
    dest: /usr/bin/dlast
    owner: root
    group: root
    mode: 0755
  tags:
    - docker
    - shell

...