---

- hosts: localhost

  vars:

    config:

      users:

        - name: ansible
          state: present
          password: changeme
          update_password: on_create
          groups: sudo
          append: yes
          # TODO: vault pw

          system: no
          hide: no

        - name: masu
          state: present
          password: changeme
          update_password: on_create
          ssh_key_bits: 128
          ssh_key_comment: masu@$HOSTNAME
          ssh_key_passphrase: ""
          groups: sudo,ansible
          append: yes
          # TODO: vault pw
          # TODO: vault passphrase

          bashrcd: yes
          bashstyle:
            names: "1;49;34"
            misc: "1;49;93"

        - name: willow
          state: present
          password: changeme
          update_password: on_create
          # TODO: vault pw

          hide: yes

        - name: rstrct
          state: present
          password: changeme
          home: /var/rstrct
          update_password: on_create
          system: no
          # TODO: vault pw

          hide: yes

      _path_aliases:

        - &dirmasu
          owner: masu
          group: masu
          state: directory
          follow: no
        - &755masu
          <<: *dirmasu
          mode: "0755"
        - &700masu
          <<: *dirmasu
          mode: "0700"

      paths:

        - <<: *755masu
          path: "/home/masu"
        - <<: *700masu
          path: "/home/masu/Downloads"
        - <<: *755masu
          path: "/home/masu/Pictures"
        - <<: *700masu
          path: "/home/masu/Downloads/torrent"
        - <<: *700masu
          path: "/home/masu/Downloads/firefox"
        - <<: *755masu
          path: "/home/masu/Downloads/torrent/ncore"
          recurse: yes
        - <<: *700masu
          path: "/home/masu/Downloads/torrent/current"
        - <<: *700masu
          path: "/home/masu/Downloads/torrent/stopped"
        - <<: *700masu
          path: "/home/masu/Downloads/torrent/watch"
        - <<: *700masu
          path: "/home/masu/Downloads/torrent/index"
        - <<: *700masu
          path: "/home/masu/Dropbox"
        - <<: *700masu
          path: "/home/masu/MEGA"
        - <<: *700masu
          path: "/home/masu/Projects"

        - path: "/home/willow/ncore"
          follow: no
          force: yes
          owner: "willow"
          group: "willow"
          src: "/home/masu/Downloads/torrent/ncore"
          state: link

        - path: "/home/ansible/.ssh/authorized_keys"
          mode: "0600"

        - path: "/var/rstrct/"
          force: yes
          mode: "0700"
          owner: rstrct
          group: rstrct
          state: directory

      repos:

        # Ubuntu repos present
        - id: deb-all
          state: present
        - id: deb-security-all
          state: present
        - id: deb-updates-all
          state: present
        - id: deb-backports-oss
          state: present

        # Ubuntu repos absent
        - id: deb-backports-all
          state: absent
        - id: deb-proposed-oss
          state: absent
        - id: deb-proposed-all
          state: absent

        # Application repos
        - dropbox
        - mega
        - git-lfs
        - slack-jessie
        - webupd8team-java
        - webupd8team-tor
        - umake
        - virtualbox
        - chrome-gnome

      _package_aliases:
        - &absent
          state: absent
          purge: yes

      pre_packages:
        - aptitude
        - apt-transport-https
        - accountsservice
        - ca-certificates
        - locales

      packages:

        # Defaults to remove
        - <<: *absent
          name: account-plugin-facebook
        - <<: *absent
          name: account-plugin-flickr
        - <<: *absent
          name: aisleriot
        - <<: *absent
          name: bogofilter
        - <<: *absent
          name: bogofilter-common
        - <<: *absent
          name: bogofilter-bdb
        - <<: *absent
          name: brasero
        - <<: *absent
          name: brasero-common
        - <<: *absent
          name: brasero-cdrkit
        - <<: *absent
          name: brltty
        - <<: *absent
          name: dc
        - <<: *absent
          name: dvd+rw-tools
        - <<: *absent
          name: espeak-data
        - <<: *absent
          name: evolution
        - <<: *absent
          name: evolution-common
        - <<: *absent
          name: evolution-data-server
        - <<: *absent
          name: evolution-data-server-common
        - <<: *absent
          name: evolution-data-server-online-accounts
        - <<: *absent
          name: evolution-plugins
        - <<: *absent
          name: folks-common
# foomatic-db-compressed-ppds
# freepats
# freerdp-x11
        - <<: *absent
          name: genisoimg
        - <<: *absent
          name: libbrasero-media3-1
        - <<: *absent
          name: gnome-mahjongg
        - <<: *absent
          name: gnome-orca
        - <<: *absent
          name: gnome-sudoku
# hunspell-en-us
# modemmanager
# mokutils
# mutter
# seahorse
# tipa
# tk
# toshset
# tracker-miner-fs
# unoconv
# wamerican
# wbritish
# webbrowser-app
# whiptail
# yelp-*

        - <<: *absent
          name: rhythmbox
        - <<: *absent
          name: rhythmbox-data
        - <<: *absent
          name: rhythmbox-plugins
        - <<: *absent
          name: rhythmbox-plugin-zeitgeist

        - <<: *absent
          name: totem
        - <<: *absent
          name: totem-common
        - <<: *absent
          name: totem-plugins

        - <<: *absent
          name: wodim

        # Ubuntu system
        - systemd
        - fakeroot
        - file
        - findutils
        - rsync
        - gparted
        - gdisk
        - baobab
        - iptables
        - macchanger
        - traceroute
        - netcat
        - telnet
        - htop
        - tree
        - rar
        - unrar
        - zip
        - unzip
        - apt
        - aptitude
        - apt-cacher-ng

        # Security
        - openvpn
        - network-manager-openvpn
        - network-manager-openvpn-gnome

        # Programming
        - git
        - gitk
        - ubuntu-make
        - g++
        - gcc
        - make
        - libc-bin
        - lsb
        - build-essential
        - gawk
        - python
        - python-pip
        - python-dev
        - python3
        - python3-pip
        - python3-dev
        - virtualenv
        - npm
        - nodejs
        - nodejs-legacy

        # Java
        - oracle-java8-installer
        - oracle-java8-set-default
        - oracle-java8-unlimited-jce-policy

        # Desktop
        - accountsservice
        - chrome-gnome-shell
        - gnome-shell-extensions
        - gnome-tweak-tool
        - shutter
        - caffeine
        - firefox
        - firefox-locale-en
        - chromium-browser
        - chromium-codecs-ffmpeg

        # Media
        - clementine
        - mplayer
        - smplayer
        - libavcodec-extra
        - ffmpeg
        - ubuntu-restricted-extras

        # Virtualisation
        - docker.io
        - docker-compose
        - virtualbox
        - vagrant

        # Office
        - vim
        - gedit
        - evince
        - pdftk
        - calibre
        - texlive
        - texstudio
        - ttf-mscorefonts-installer
        - ttf-ubuntu-font-family
        - libfreetype6
        - libfreetype6-dev
        - libfontconfig
        - fonts-ubuntu-font-family-console
        - eog
        - pinta
        - gimp
        - inkscape
        - libreoffice-writer
        - libreoffice-calc
        - libreoffice-impress

        # Transimission
        - curl
        - wget
        - youtube-dl
        - deluged
        - deluge-gtk
        - deluge-console
        - deluge-webui
#        - skype
#        - gtk2-engines-murrine
#        - gtk2-engines-pixbuf
        - empathy
        - cheese
        - dropbox
        - megasync
        - megatools

        # Remote access
        - openssh-server
        - vnc4server
        - xrdp
        - rdesktop
        - vinagre
        - synergy

      python3_packages:

        # Dev
        - tqdm
        - pytz
        - cython
        - selenium

        # Data science
        - numpy
        - scipy
        - scikit-learn
        - xgboost
        - pandas
        - matplotlib
        - seaborn
        - beautifulsoup

        # Interface
        - ipython
        - ipywidgets
        - jupyter
        - jupyter-declarativewidgets

        # tools
        - pymongo
        - py4j
        - pyinstaller
        - thefuck

      gnome_settings:
        - id: keyboard_layouts
          value: "[('xkb', 'hu'), ('xkb', 'us')]"
          state: present
#        - id: keyboard_layout
#          value: 0
#          state: present
#        - id: keyboard_layout_per_window
#          value: no
#          state: present
#        - id: keyboard_layout_show_all
#          value: no
#          state: present
#        - id: keyboard_xkb_options
#          value: 'terminate:ctrl_alt_bksp'
#          state: present

      # TODO keyboard layout
      # TODO background and co
      # TODO power options
      # TODO sound settings

  pre_tasks:

    - name: install prerequisite packages
      become: yes
      apt:
        package: "{{ item }}"
      with_items: "{{ config.pre_packages }}"
      tags:
        - apt
        - download

  roles:

#    - role: _users
#      users: "{{ config.users }}"
#      tags:
#        - user
#        - password
#
#    - role: _paths
#      users: "{{ config.users }}"
#      tags:
#        - user
#        - password
#
#    - role: _apt_repos
#      repos: "{{ config.repos }}"
#      empty_sources_list: yes
#      update_cache: yes
#      tags:
#        - repository
#        - apt
#        - download
#
#    - role: _apt_packages
#      packages: "{{ config.packages }}"
#      tags:
#        - package
#        - apt
#        - download
#
#    - role: netlimit
#      users:
#        - root
#        - masu
#      tags:
#        - security
#        - network

    - role: _gnome_settings
      gnome_settings: "{{ config.gnome_settings }}"

  tasks:

      # TODO environment variables
      # TODO aliases
      # TODO startup applications
      # TODO application configurations
        # TODO docker settings (dlast, docker group, etc)
        # TODO VNC server
        # TODO firefox
        # TODO dropbox
        # TODO megasync
        # TODO ssh
        # TODO VPN
        # TODO deluge
        # TODO idea
        # TODO git
        # TODO project repos git
        # TODO apt-cacher-ng

#    - name: set python packages
#      become: yes
#      pip:
#        executable: pip3
#        name: "{{ package }}"
#      with_items: "{{ config.python3_packages }}"
#      loop_control:
#        loop_var: package
#      tags:
#        - download
#        - programming
#        - python
#
#    - name: set python aliases
#      become: yes
#      blockinfile:
#        backup: yes
#        block: |
#          alias python=python3
#          alias pip=pip3
#          alias ipython=ipython3
#        create: yes
#        follow: yes
#        group: masu
#        insertafter: EOF
#        marker: "# {mark} ANSIBLE MANAGED BLOCK - python alias"
#        mode: "0664"
#        owner: masu
#        path: "/home/masu/.profile"
#        state: present
#      tags:
#        - programming
#        - python
#        - shell
#
#    - name: set firefox-bme alias
#      become: yes
#      blockinfile:
#        backup: yes
#        block: |
#          alias firefox-bme=ssh\ -D\ 8080\ -f\ -C\ -c\ blowfish-cbc\ -q\ masu@ede.tmit.bme.hu\ sleep\ 10\;\\
#          firefox\ -P\ bme
#        create: yes
#        follow: yes
#        group: masu
#        insertafter: EOF
#        marker: "# {mark} ANSIBLE MANAGED BLOCK - firefox-bme alias"
#        mode: "0664"
#        owner: masu
#        path: "/home/masu/.profile"
#        state: present
#      tags:
#        - network
#        - bme
#        - shell
#
#    - name: nodejs packages
#      become: yes
#      npm:
#        name: "{{ item }}"
#        global: yes
#        state: present
#      with_items:
#        - phantomjs-prebuilt
#      tags:
#        - npm
#        - package
#        - download
#
#    - name: apt upgrade & cleanup
#      become: yes
#      apt:
#        purge: yes
#        upgrade: full
#        autoremove: yes
#      tags:
#        - package
#        - apt
#        - network

...