---

- name: prerequisites, users and paths
  hosts: mymachine
  pre_tasks:

    - name: install prerequisite packages
      when: ansible_os_family == "Debian"
      become: yes
      apt:
        package: "{{ item }}"
      with_items:
        - aptitude
        - apt-transport-https
        - accountsservice
        - ca-certificates
        - locales
      tags:
        - apt
        - download

    - name: install prerequisite packages
      when: ansible_os_family == "Archlinux"
      become: yes
      pacman:
        package: "{{ item }}"
      with_items:
        - ca-certificates
      tags:
        - pacman
        - download

  roles:

    - role: _users
      vars:
        sudo: "{{ {
              'Debian': 'sudo',
              'Archlinux': 'wheel',
            }[ansible_os_family]
          }}"
      users:

        - name: ansible
          state: present
          password: "{{ passwords.ansible }}"
          update_password: on_create
          groups: "{{ sudo }}"
          append: yes
          shell: /bin/bash

          hide: yes

        - name: masu
          state: present
          password: "{{ passwords.masu }}"
          update_password: always
          ssh_key_bits: 128
          ssh_key_comment: masu@$HOSTNAME
          ssh_key_passphrase: "{{ passphrases.masu }}"
          groups: "{{ sudo }},ansible"
          append: yes
          shell: /bin/bash

          hide: no
          bashrcd: yes
          bashstyle:
            names: "1;49;34"
            misc: "1;49;93"

          bookmarks:
            append: no
            bookmarks:
              - /home/masu/Documents
              - /home/masu/Downloads
              - ""
              - /home/masu/Desktop Desktop
              - /home/masu/MEGA MEGA
              - /home/masu/Dropbox Dropbox

        - name: willow
          state: present
          password: "{{ passwords.willow }}"
          update_password: on_create
          system: no
          shell: /bin/bash

          hide: yes

        - name: rstrct
          state: present
          password: "{{ passwords.rstrct }}"
          home: /var/rstrct
          update_password: on_create
          system: no
          shell: /bin/bash

          hide: yes

      tags:
        - user
        - password

    - role: _paths
      __paths:
        - &dirmasu
          owner: masu
          group: masu
          state: directory
          follow: no
        - &755masu
          <<: *dirmasu
          mode: "0755"
        - &700masu
          <<: *dirmasu
          mode: "0700"
        - &777masu
          <<: *dirmasu
          mode: "0777"
      paths:
        - <<: *755masu
          path: "/home/masu"
        - <<: *700masu
          path: "/home/masu/Downloads"
        - <<: *755masu
          path: "/home/masu/Pictures"
        - <<: *777masu
          path: "/home/masu/Willow"
        - path: "/home/willow/Masu"
          follow: no
          force: yes
          owner: "willow"
          group: "willow"
          src: "/home/masu/Willow"
          state: link
        - path: "/home/ansible/.ssh/"
          mode: "0600"
          state: directory
        - path: "/var/rstrct/"
          force: yes
          mode: "0700"
          owner: rstrct
          group: rstrct
          state: directory

      tags:
        - user
        - password

- name: repos
  hosts: mymachine
  roles:

    - when: ansible_os_family == "Debian"
      role: _apt_repos
      repos:
        # Ubuntu repos
        - id: deb-main
          state: present
        - id: deb-ext
          state: present
        - id: deb-security-all
          state: present
        - id: deb-updates-all
          state: present
        - id: deb-backports-oss
          state: present
        # Application repos
        - id: dropbox
          release: xenial  # TODO: reconsider release
        - mega
        - webupd8team
        - id: umake
          release: zesty  # TODO: reconsider release
        - id: chrome-gnome
          release: zesty  # TODO: reconsider release
      empty_sources_list: yes
      update_cache: yes
      tags:
        - repository
        - apt
        - download

- name: default packages to remove
  hosts: mymachine
  tasks:

    - when: ansible_os_family == "Debian"
      name: apt packages to remove
      become: yes
      apt:
        name: "{{ package }}"
        state: absent
        purge: yes
      loop_control:
        loop_var: package
      tags:
        - package
        - apt
      with_items:
        - account-plugin-facebook
        - account-plugin-flickr
        - aisleriot
        - bogofilter
        - bogofilter-common
        - bogofilter-bdb
        - brasero
        - brasero-common
        - brasero-cdrkit
        - brltty
        - dc
        - dvd+rw-tools
        - espeak-data
        - genisoimg
        - libbrasero-media3-1
        - gnome-mahjongg
        - gnome-orca
        - gnome-sudoku
        - rhythmbox
        - rhythmbox-data
        - rhythmbox-plugins
        - rhythmbox-plugin-zeitgeist
        - totem
        - totem-common
        - totem-plugins
        - wodim

    - when: ansible_os_family == "Archlinux"
      name: pacman packages to remove
      pacman:
        name: "{{ package }}"
        state: absent
      loop_control:
        loop_var: package
      tags:
        - package
        - pacman
      with_items: []

- name: packages
  hosts: mymachine
  vars:
    common_packages:
      system:
        - systemd
        - fakeroot
        - file
        - findutils
        - rsync
        - gparted
        - baobab
        - iptables
        - macchanger
        - traceroute
        - htop
        - tree
        - unrar
        - zip
        - unzip
        - openvpn
        - |
          {{
            {
              'Debian': 'telnet',
              'Archlinux': 'inetutils'
            }[ansible_os_family]
          }}
        - |
          {{
            {
              'Debian': 'netcat',
              'Archlinux': 'gnu-netcat'
            }[ansible_os_family]
          }}
      programming:
        - |
          {{
            {
              'Debian': 'python3',
              'Archlinux': 'python'
            }[ansible_os_family]
          }}
        - git
        - gawk
      desktop:
        - accountsservice
        - firefox
        - |
          {{
            {
              'Debian': 'shutter',
              'Archlinux': 'spectacle'
            }[ansible_os_family]
          }}
        - |
          {{
            {
              'Debian': 'chromium-browser',
              'Archlinux': 'chromium'
            }[ansible_os_family]
          }}
      media:
        - clementine
        - mplayer
        - smplayer
        - ffmpeg
        - vlc
      virtual:
        - docker-compose
        - virtualbox
        - vagrant
        - |
          {{
            {
              'Debian': 'docker.io',
              'Archlinux': 'docker'
            }[ansible_os_family]
          }}
      office:
        - vim
        - gedit
        - evince
        - calibre
        - pinta
        - gimp
        - inkscape
        # TODO: check for debian libreoffice package
        - |
          {{
            {
              'Debian': 'hunspell-en-us',
              'Archlinux': 'hunspell'
            }[ansible_os_family]
          }}
        - |
          {{
            {
              'Debian': 'libreoffice-writer',
              'Archlinux': 'libreoffice'
            }[ansible_os_family]
          }}
        - |
          {{
            {
              'Debian': 'libreoffice-calc',
              'Archlinux': 'libreoffice'
            }[ansible_os_family]
          }}
        - |
          {{
            {
              'Debian': 'libreoffice-impress',
              'Archlinux': 'libreoffice'
            }[ansible_os_family]
          }}
      transmission:
        - curl
        - wget
        - youtube-dl
        # TODO: check for deluge debian package
        - |
          {{
            {
              'Debian': 'deluge-gtk',
              'Archlinux': 'deluge'
            }[ansible_os_family]
          }}
        - cheese
      remote:
        - |
          {{
            {
              'Debian': 'openssh-server',
              'Archlinux': 'openssh'
            }[ansible_os_family]
          }}
        - paprefs
        - rdesktop
        - synergy
    ubuntu_packages:
      system:
        - rar
        - apt
        - aptitude
        - galternatives
        - network-manager-openvpn
        - network-manager-openvpn-gnome
      programming:
        - ubuntu-make
        - python3
        - python3-dev
        - python3-setuptools
        - python3-pip
        - virtualenv
      desktop:
        - chrome-gnome-shell
        - gnome-shell-extensions
        - gnome-tweak-tool
        - caffeine
      media:
      virtual:
      office:
#        - pdftk  # TODO: consider readding
      transmission:
        - slack
        - dropbox
        - megasync
      remote:
    manjaro_packages:
      system:
        - netcat  # TODO: fix error?!
        - yaourt
      programming:
        - python3  # TODO: fix error?!
      desktop:
#        - caffeine-ng  # TODO: install with yaourt
      media:
      virtual:
      office:
#        - pdftk  # TODO: install with yaourt
        - libreoffice
        - hunspell
      transmission:
#        - slack  # TODO: install with yaourt
#        - dropbox  # TODO: install with yaourt
#        - megasync  # TODO: install with yaourt
      remote:

  tasks:

    - name: common packages
      become: yes
      package:
        name: "{{ package }}"
        state: present
      loop_control:
        loop_var: package
      tags:
        - package
        - download
      with_items: |
        {{
          common_packages.values()
          | flatten
          | map('trim')
          | list
        }}

    - when: ansible_os_family == "Debian"
      name: apt packages
      become: yes
      apt:
        name: "{{ package }}"
        state: present
      loop_control:
        loop_var: package
      tags:
        - package
        - apt
        - download
      with_items: |
        {{
          ubuntu_packages.values()
          | flatten
          | map('trim')
          | list
        }}

    - when: ansible_os_family == "Archlinux"
      name: pacman packages
      become: yes
      pacman:
        name: "{{ package }}"
        state: present
      loop_control:
        loop_var: package
      tags:
        - package
        - pacman
        - download
      with_items: |
        {{
          ubuntu_packages.values()
          | flatten
          | map('trim')
          | list
        }}

- name: netlimit
  hosts: mymachine
  roles:

    - role: netlimit
      users:
        - root
        - masu
      tags:
        - security
        - network

- name: docker
  hosts: mymachine
  tasks:

    - name: docker group
      become: yes
      user:
        name: masu
        groups: docker
        append: yes
      tags:
        - docker
        - user
        - group

    - name: dl command
      become: yes
      copy:
        content: !unsafe |
          #!/bin/bash

          docker ps -l -q
        dest: /usr/bin/dlast
        owner: root
        group: root
        mode: 0755
      tags:
        - docker
        - shell

- name: python3
  hosts: mymachine
  tasks:

    - name: set python3 packages
      become: yes
      pip:
        state: latest
        executable: pip3
        name: "{{ package }}"
      loop_control:
        loop_var: package
      tags:
        - download
        - programming
        - python
        - package
      with_items:
        # Dev
        - tqdm
        - pytz
        - cython
        - selenium

        # Data science
        - numpy
        - scipy
        - scikit-learn
        - xgboost
        - pandas
        - matplotlib
        - seaborn

        # Interface
        - ipython
        - ipywidgets
        - jupyter
        - jupyter-declarativewidgets
        # tools
        - pymongo
        - py4j
        - pyinstaller
        - thefuck

- name: update and upgrade
  hosts: mymachine
  tasks:

    - when: ansible_os_family == 'Debian'
      name: apt upgrade
      become: yes
      apt:
        autoremove: yes
        force: yes
        purge: yes
        upgrade: full
      tags:
        - package
        - apt
        - network

    - when: ansible_os_family == 'Archlinux'
      name: pacman upgrade
      become: yes
      pacman:
        force: yes
        update_cache: yes
        upgrade: yes
      tags:
        - package
        - pacman
        - network

- name: environment settings
  hosts: mymachine
  tasks:

    - name: set login keyboard layout
      become: yes
      lineinfile:
        path: /etc/default/keyboard
        line: XKBLAYOUT="hu"
        regexp: ^XKBLAYOUT=.*$
      tags:
        - desktop
        - settings

    - name: set firefox socket proxy tunnel alias
      become: yes
      copy:
        backup: yes
        content: !unsafe |
          #!/bin/bash
          ssh -D 22344 -f -C -c aes256-ctr -q $@ sleep 10
          firefox -P proxy22344 &
        dest: "/usr/bin/proxyfox"
        follow: yes
        group: root
        mode: "0755"
        owner: root
      tags:
        - network
        - shell

...