---

- import_playbook: pb_prerequisites.yml

- import_playbook: pb_users_paths.yml
  vars:

    users:

      - name: ansible
        state: present
        password: "{{ passwords.ansible }}"
        update_password: on_create
        groups: "{{ sudo }}"
        append: yes
        shell: /bin/bash

        hide: yes

      - name: masu
        state: present
        password: "{{ passwords.masu }}"
        update_password: always
        ssh_key_bits: 128
        ssh_key_comment: masu@$HOSTNAME
        ssh_key_passphrase: "{{ passphrases.masu }}"
        groups: "{{ sudo }},ansible"
        append: yes
        shell: /bin/bash

        hide: no
        bashrcd: yes
        bashstyle:
          names: "1;49;34"
          misc: "1;49;93"

        bookmarks:
          append: no
          bookmarks:
            - /home/masu/Documents
            - /home/masu/Downloads
            - ""
            - /home/masu/Desktop Desktop
            - /home/masu/MEGA MEGA
            - /home/masu/Dropbox Dropbox

      - name: willow
        state: present
        password: "{{ passwords.willow }}"
        update_password: on_create
        system: no
        shell: /bin/bash

        hide: yes

      - name: rstrct
        state: present
        password: "{{ passwords.rstrct }}"
        home: /var/rstrct
        update_password: on_create
        system: no
        shell: /bin/bash

        hide: yes

    __paths:
      - &dirmasu
        owner: masu
        group: masu
        state: directory
        follow: no
      - &755masu
        <<: *dirmasu
        mode: "0755"
      - &700masu
        <<: *dirmasu
        mode: "0700"
      - &777masu
        <<: *dirmasu
        mode: "0777"

    paths:
      - <<: *755masu
        path: "/home/masu"
      - <<: *700masu
        path: "/home/masu/Downloads"
      - <<: *755masu
        path: "/home/masu/Pictures"
      - <<: *777masu
        path: "/home/masu/Willow"
      - path: "/home/willow/Masu"
        follow: no
        force: yes
        owner: "willow"
        group: "willow"
        src: "/home/masu/Willow"
        state: link
      - path: "/home/ansible/.ssh/"
        mode: "0600"
        state: directory
      - path: "/var/rstrct/"
        force: yes
        mode: "0700"
        owner: rstrct
        group: rstrct
        state: directory

- import_playbook: pb_repos_packages.yml
  vars:

    upgrade: yes

    repo_config:
      Ubuntu:
        - deb-main
        - deb-ext
        - deb-security-all
        - deb-updates-all
        - deb-backports-oss
        - dropbox
        - mega
        - webupd8team
      ManjaroLinux: []  # TODO: Aur pg keys

    package_config:
      # System
      - gcc
      - Ubuntu: build-essentials
        ManjaroLinux: base-devel
      - systemd
      - rsync
      - iptables
      - traceroute
      - htop
      - rar
      - zip
      - Ubuntu: telnet
        ManjaroLinux: inetutils
      - Ubuntu: netcat
        ManjaroLinux: gnu-netcat
      - Ubuntu: bluez
        ManjaroLinux: bluez-utils
      - Ubuntu: dnsutils  # TODO: check this
        ManjaroLinux: dnsutils
      - Ubuntu: apt
      - Ubuntu: aptitude
      - Ubuntu: galternatives
      - fakeroot

      # Programming
      - Ubuntu: python3-dev
        ManjaroLinux: python
      - Ubuntu: python3-setuptools
        ManjaroLinux: python-setuptools
      - git
      - gawk

      # Desktop
      - accountsservice
      - firefox
      - Ubuntu: shutter
        ManjaroLinux: spectacle
      - Ubuntu: chromium-browser"
        ManjaroLinux: chromium
      - Ubuntu: slack
        ManjaroLinux: slack-desktop

      # Media
      - smplayer
      - ffmpeg
      - vlc
      - Ubuntu:
          name: rhythmbox rhythmbox-data rhythmbox-plugins rhythmbox-plugin-zeitgeist totem totem-common totem-plugins
          state: absent

      # Virtual
      - Ubuntu: docker.io
        ManjaroLinux: docker
      - Ubuntu: virtualbox
        ManjaroLinux: virtualbox
      - ManjaroLinux: "linux{{ ansible_kernel.split('.')[:2] | join }}-virtualbox-host-modules"
      - Ubuntu: vagrant
        ManjaroLinux: vagrant

      # Office
      - vim
      - kate
      - pinta
      - Ubuntu: hunspell-en-us"
        ManjaroLinux: hunspell
        # TODO: pdftk

      # Transmission
      - curl
      - wget
      - deluge
      - Ubuntu: dropbox
        ManjaroLinux: dropbox
      - Ubuntu: megasync
        ManjaroLinux: megasync

      # Remote
      - Ubuntu: openssh-server
        ManjaroLinux: openssh
      - rdesktop
      - synergy

    python3_packages:
      # Data science
      - numpy
      - scipy
      - scikit-learn
      - xgboost
      - pandas
      - matplotlib
      - seaborn

      # Scrape
      - beautifulsoup4
      - selenium
      - jmespath

      # Interface
      - ipython
      - ipywidgets
      - jupyter
      - jupyter-declarativewidgets

      # Tools
      - pyinstaller
      - xlrd
      - xlwt
      - tqdm
      - pytz
      - cython

      # Desktop
      - thefuck
      - caffeine-ng

- import_playbook: pb_netlimit.yml
  vars:
    users:
      - root
      - masu

- import_playbook: pb_docker.yml
  vars:
    users:
      - masu

- import_playbook: pb_env.yml
  vars:
    xkblayout: hu
    proxyport: 22344

...