---

- import_playbook: pb_prerequisites.yml
- import_playbook: pb_users_paths.yml
- import_playbook: pb_repos_packages.yml
- import_playbook: pb_app_config.yml
- import_playbook: pb_desktop_settings.yml

...