---

- name: environment settings
  hosts: all
  tasks:

    - when: xkblayout is defined
      name: set login keyboard layout
      become: yes
      lineinfile:
        path: /etc/default/keyboard
        line: "XKBLAYOUT=\"{{xkblayout}}\""
        regexp: ^XKBLAYOUT=.*$
      tags:
        - desktop
        - settings

    - when: proxyport is defined
      name: set firefox socket proxy tunnel alias
      become: yes
      copy:
        backup: yes
        content: !unsafe |
          #!/bin/bash
          ssh -D {{proxyport}} -f -C -c aes256-ctr -q $@ sleep 10
          firefox -P proxy{{proxyport}} &
        dest: "/usr/bin/proxyfox"
        follow: yes
        group: root
        mode: "0755"
        owner: root
      tags:
        - network
        - shell

...