---

- name: repos
  hosts: mymachine

  roles:

    - install

#    - name: set python3 packages
#      become: yes
#      pip:
#        state: latest
#        executable: pip3
#        name:
#          - pip
#          - setuptools
#      tags:
#        - download
#        - programming
#        - python
#        - package
#
#    - name: set python3 packages
#      become: yes
#      pip:
#        state: latest
#        executable: pip3
#        name: "{{ python3_packages }}"
#      tags:
#        - download
#        - programming
#        - python
#        - package
#
#...