---

- name: repos
  hosts: all

  vars:

    ubuntu_repos:
      - id: deb-main
        state: present
      - id: deb-ext
        state: present
      - id: deb-security-all
        state: present
      - id: deb-updates-all
        state: present
      - id: deb-backports-oss
        state: present
      - id: dropbox
        release: xenial  # TODO: reconsider release
      - mega
      - webupd8team
      - bionic-pdf
      - id: umake
        release: zesty  # TODO: reconsider release
      - id: chrome-gnome
        release: zesty  # TODO: reconsider release

  pre_tasks:

    - assert:
        that:
          - debian_repos is defined
          - arch_repos is defined
          - redhat_repos is defined

  roles:

    - when: ansible_os_family == "Debian"
      name: set apt repositories
      role: _apt_repos
      repos: "{{ debian_repos }}"
      tags:
        - repository
        - apt
        - download

    - when: ansible_os_family == "RedHat"
      name: set yum repositories
      role: _yum_repos
      repos: "{{ redhat_repos }}"
      tags:
        - repository
        - yum
        - download

- name: packages
  hosts: all

  vars:
    ubuntu_absent_packages:
      - account-plugin-facebook
      - account-plugin-flickr
      - aisleriot
      - bogofilter
      - bogofilter-common
      - bogofilter-bdb
      - brasero
      - brasero-common
      - brasero-cdrkit
      - brltty
      - dc
      - dvd+rw-tools
      - espeak-data
      - genisoimg
      - libbrasero-media3-1
      - gnome-mahjongg
      - gnome-orca
      - gnome-sudoku
      - rhythmbox
      - rhythmbox-data
      - rhythmbox-plugins
      - rhythmbox-plugin-zeitgeist
      - totem
      - totem-common
      - totem-plugins
      - wodim
    manjaro_absent_packages:
      - brasero
    common_packages:
      # System
      - systemd
      - fakeroot
      - file
      - findutils
      - rsync
      - gparted
      - baobab
      - iptables
      - macchanger
      - traceroute
      - htop
      - tree
      - rar
      - unrar
      - zip
      - unzip
      - openvpn
      - "{{ {
          'Debian': 'telnet',
          'Archlinux': 'inetutils',
        }[ansible_os_family] }}"
      - "{{ {
          'Debian': 'netcat',
          'Archlinux': 'gnu-netcat',
        }[ansible_os_family] }}"
      - "{{ {
          'Debian': 'bluez',
          'Archlinux': 'bluez-utils',
        }[ansible_os_family] }}"

      # Programming
      - "{{ {
          'Debian': 'python3',
          'Archlinux': 'python',
        }[ansible_os_family] }}"
      - "{{ {
          'Debian': 'python3-pip',
          'Archlinux': 'python-pip',
        }[ansible_os_family] }}"
      - "{{ {
          'Debian': 'python3-setuptools',
          'Archlinux': 'python-setuptools',
        }[ansible_os_family] }}"
      - git
      - gawk
      - phantomjs

      # Desktop
      - accountsservice
      - firefox
      - "{{ {
          'Debian': 'shutter',
          'Archlinux': 'spectacle',
        }[ansible_os_family] }}"
      - "{{ {
          'Debian': 'chromium-browser',
          'Archlinux': 'chromium',
          }[ansible_os_family]
        }}"
      - "{{ {
          'Debian': 'caffeine',
          'Archlinux': 'caffeine-ng',
        }[ansible_os_family] }}"

      # Media
      - clementine
      - mplayer
      - smplayer
      - ffmpeg
      - vlc

      # Virtual
      - docker-compose
      - virtualbox
      - vagrant
      - "{{ {
          'Debian': 'docker.io',
          'Archlinux': 'docker',
        }[ansible_os_family] }}"

      # Office
      - vim
      - gedit
      - evince
      - calibre
      - pinta
      - gimp
      - inkscape
      - "{{ {
          'Debian': 'hunspell-en-us',
          'Archlinux': 'hunspell',
        }[ansible_os_family] }}"
      - "{{ {
          'Debian': 'libreoffice',
          'Archlinux': 'libreoffice-fresh',
        }[ansible_os_family] }}"
      - pdftk

      # Transmission
      - curl
      - wget
      - youtube-dl
      - deluge
      - cheese
      - "{{ {
          'Debian': 'slack',
          'Archlinux': 'slack-desktop',
        }[ansible_os_family] }}"
      - dropbox
      - megasync

      # Remote
      - "{{ {
          'Debian': 'openssh-server',
          'Archlinux': 'openssh',
        }[ansible_os_family] }}"
      - paprefs
      - rdesktop
      - synergy
    ubuntu_packages:
      - apt
      - aptitude
      - galternatives
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - python3-dev
      - virtualenv
      - chrome-gnome-shell
      - gnome-shell-extensions
      - gnome-tweak-tool
    manjaro_packages:
      - "linux{{ ansible_kernel.split('.')[:2] | join }}-virtualbox-host-modules"
      - virtualbox-ext-oracle
    python3_packages:
      # Dev
      - tqdm
      - pytz
      - cython
      - selenium
      - lxml

      # Data science
      - numpy
      - scipy
      - scikit-learn
      - xgboost
      - pandas
      - matplotlib
      - seaborn
      - beautifulsoup4

      # Interface
      - ipython
      - ipywidgets
      - jupyter
      - jupyter-declarativewidgets

      # Tools
      - pymongo
      - py4j
      - pyinstaller
      - thefuck

  pre_tasks:

    - assert:
        that:

          - redhat_python is defined

          - common_packages is defined
          - debian_packages is defined
          - arch_packages is defined
          - redhat_packages is defined

          - python3_packages is defined

          - debian_absent_packages is defined
          - arch_absent_packages is defined
          - redhat_absent_packages is defined

  tasks:

    - when: ansible_os_family == "Debian"
      name: empty source.list
      become: yes
      copy:
        backup: yes
        content: ""
        dest: /etc/apt/sources.list

    - when: ansible_os_family == "Debian"
      name: apt packages to remove
      become: yes
      apt:
        name: "{{ debian_absent_packages }}"
        state: absent
        purge: yes
      tags:
        - package
        - apt

    - when: ansible_os_family == "Archlinux"
      name: pacman packages to remove
      pacman:
        name: "{{ arch_absent_packages }}"
        state: absent
      tags:
        - package
        - pacman

    - when: ansible_os_family == "RedHat"
      name: yum packages to remove
      yum:
        name: "{{ redhat_absent_packages }}"
        state: absent
      tags:
        - package
        - yum

    - when: ansible_os_family == "Debian"
      name: apt packages
      become: yes
      apt:
        name: "{{ common_packages + debian_packages }}"
        state: present
      tags:
        - package
        - apt
        - download

    - when: ansible_os_family == "Archlinux"
      aur:
        name: "{{ package }}"
        auronly: no
      loop_control:
        loop_var: package
      tags:
        - package
        - pacman
        - aur
        - download
      with_items: "{{ common_packages + arch_packages }}"

    - when: ansible_os_family == "RedHat"
      name: yum packages
      become: yes
      yum:
        name: "{{ common_packages + redhat_packages }}"
        state: present
      tags:
        - package
        - yum
        - download

    - when: ansible_os_family == "RedHat"
      name: set pip3
      become: yes
      copy:
        content: |
          #!/bin/{{ redhat_python }}

          # -*- coding: utf-8 -*-
          import re
          import sys

          from pip._internal import main

          if __name__ == '__main__':
              sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
              sys.exit(main())

        mode: 755
        owner: root
        group: root
        dest: /usr/bin/pip3
      tags:
        - programming
        - python
        - package

    - name: set python3 packages
      become: yes
      pip:
        state: latest
        executable: pip3
        name:
          - pip
          - setuptools
      tags:
        - download
        - programming
        - python
        - package

    - name: set python3 packages
      become: yes
      pip:
        state: latest
        executable: pip3
        name: "{{ python3_packages }}"
      tags:
        - download
        - programming
        - python
        - package

    - when: ansible_os_family == 'Debian'
      name: apt upgrade
      become: yes
      apt:
        autoremove: yes
        force: yes
        purge: yes
        upgrade: full
      tags:
        - package
        - apt
        - network

    - when: ansible_os_family == 'Archlinux'
      name: pacman upgrade
      become: yes
      pacman:
        force: yes
        update_cache: yes
        upgrade: yes
      tags:
        - package
        - pacman
        - network

    - when: ansible_os_family == 'RedHat'
      name: yum upgrade
      become: yes
      yum:
        name: '*'
        state: latest
        update_cache: yes
      tags:
        - package
        - yum
        - network

...