---

- name: repos
  hosts: all

  pre_tasks:

    - assert:
        that:
          - ubuntu_repos is defined

  roles:

    - when: ansible_os_family == "Debian"
      name: set repositories
      role: _apt_repos
      repos: "{{ ubuntu_repos }}"
      empty_sources_list: yes
      update_cache: yes
      tags:
        - repository
        - apt
        - download

- name: packages
  hosts: all

  pre_tasks:

    - assert:
        that:
          - common_packages is defined
          - ubuntu_packages is defined
          - manjaro_packages is defined
          - python3_packages is defined
          - ubuntu_absent_packages is defined
          - manjaro_absent_packages is defined

  tasks:

    - when: ansible_os_family == "Debian"
      name: empty source.list
      become: yes
      copy:
        backup: yes
        content: ""
        dest: /etc/apt/sources.list

    - when: ansible_os_family == "Debian"
      name: apt packages to remove
      become: yes
      apt:
        name: "{{ ubuntu_absent_packages }}"
        state: absent
        purge: yes
      tags:
        - package
        - apt

    - when: ansible_os_family == "Archlinux"
      name: pacman packages to remove
      pacman:
        name: "{{ manjaro_absent_packages }}"
        state: absent
      tags:
        - package
        - pacman

    - when: ansible_os_family == "Debian"
      name: apt packages
      become: yes
      apt:
        name: "{{ common_packages + ubuntu_packages }}"
        state: present
      tags:
        - package
        - apt
        - download

    - when: ansible_os_family == "Archlinux"
      aur:
        name: "{{ package }}"
        auronly: no
      loop_control:
        loop_var: package
      tags:
        - package
        - pacman
        - aur
        - download
      with_items: "{{ common_packages + manjaro_packages }}"

    - name: set python3 packages
      become: yes
      pip:
        state: latest
        executable: pip3
        name: "{{ python3_packages }}"
      tags:
        - download
        - programming
        - python
        - package

    - when: ansible_os_family == 'Debian'
      name: apt upgrade
      become: yes
      apt:
        autoremove: yes
        force: yes
        purge: yes
        upgrade: full
      tags:
        - package
        - apt
        - network

    - when: ansible_os_family == 'Archlinux'
      name: pacman upgrade
      become: yes
      pacman:
        force: yes
        update_cache: yes
        upgrade: yes
      tags:
        - package
        - pacman
        - network

...