---

- name: users and paths
  hosts: all
  vars:

      sudo_group: |
        {{ {
          'Debian': 'sudo',
          'Archlinux': 'wheel',
        }[ansible_os_family] }}
      users:
        - name: ansible
          password: "{{ passwords.ansible }}"
          update_password: on_create
          system: no
          groups: "{{ sudo_group }}"
          append: yes
        - name: masu
          password: "{{ passwords.masu }}"
          update_password: on_create
          system: no
          groups: "{{ sudo_group }},ansible"
          append: yes
        - name: willow
          password: "{{ passwords.willow }}"
          update_password: on_create
          system: no
        - name: rstrct
          password: "{{ passwords.rstrct }}"
          home: /var/rstrct
          update_password: on_create
          system: no
      hidden_users:
        - willow
        - ansible
        - rstrct
      bashrcd_users:
        - masu
        - willow
      user_colors:
        masu:
          names: "1;49;34"
          misc: "1;49;93"
      __paths:
        - &dirmasu
          owner: masu
          group: masu
          state: directory
          follow: no
        - &755masu
          <<: *dirmasu
          mode: "0755"
        - &700masu
          <<: *dirmasu
          mode: "0700"
        - &777masu
          <<: *dirmasu
          mode: "0777"
      paths:
        - <<: *755masu
          path: "/home/masu"
        - <<: *700masu
          path: "/home/masu/Downloads"
        - <<: *755masu
          path: "/home/masu/Pictures"
        - <<: *777masu
          path: "/home/masu/Willow"
        - path: "/home/willow/Masu"
          follow: no
          force: yes
          owner: "willow"
          group: "willow"
          src: "/home/masu/Willow"
          state: link
        - path: "/home/ansible/.ssh/"
          mode: "0600"
          state: directory
        - path: "/var/rstrct/"
          force: yes
          mode: "0700"
          owner: rstrct
          group: rstrct
          state: directory
      user_bookmarks:
        masu:
          top: yes
          override: no
          bookmarks:
            - path: /home/masu/Documents
              name: Documents
            - path: /home/masu/Downloads
              name: Downloads
            - path: /home/masu/IdeaProjects
              name: Projects
            - path: /home/masu/Desktop
              name: Desktop
            - path: /home/masu/MEGA
              name: MEGA
            - path: /home/masu/Dropbox
              name: Dropbox
      user_avatars:
        masu: masu_avatar.png

  roles:

    - role: users

  post_tasks:

    - name: Set up paths
      become: yes
      file:
        attributes:    "{{ path.attributes    | d(omit) }}"
        attr:          "{{ path.attr          | d(omit) }}"
        follow:        "{{ path.follow        | d(omit) }}"
        force:         "{{ path.force         | d(omit) }}"
        group:         "{{ path.group         | d(omit) }}"
        mode:          "{{ path.mode          | d(omit) }}"
        owner:         "{{ path.owner         | d(omit) }}"
        path:          "{{ path.path          | d(omit) }}"
        recurse:       "{{ path.recurse       | d(omit) }}"
        selevel:       "{{ path.selevel       | d(omit) }}"
        serole:        "{{ path.serole        | d(omit) }}"
        setype:        "{{ path.setype        | d(omit) }}"
        seuser:        "{{ path.seuser        | d(omit) }}"
        src:           "{{ path.src           | d(omit) }}"
        state:         "{{ path.state         | d(omit) }}"
        unsafe_writes: "{{ path.unsafe_writes | d(omit) }}"
      with_items: "{{ paths }}"
      loop_control:
        loop_var: path
      tags:
        - user
        - file

...