---

- name: users and paths
  hosts: mymachine

  pre_tasks:

    - assert:
        that:
          - users is defined
          - paths is defined

  roles:

    - role: users
      vars:
        sudo: "{{ {
                'Debian': 'sudo',
                'Archlinux': 'wheel',
                'RedHat': 'wheel',
               }[ansible_os_family] }}"
      tags:
        - user
        - password

  post_tasks:

    - name: Set up path
      become: yes
      file:
        attributes:    "{{ path.attributes    | d(omit) }}"
        attr:          "{{ path.attr          | d(omit) }}"
        follow:        "{{ path.follow        | d(omit) }}"
        force:         "{{ path.force         | d(omit) }}"
        group:         "{{ path.group         | d(omit) }}"
        mode:          "{{ path.mode          | d(omit) }}"
        owner:         "{{ path.owner         | d(omit) }}"
        path:          "{{ path.path          | d(omit) }}"
        recurse:       "{{ path.recurse       | d(omit) }}"
        selevel:       "{{ path.selevel       | d(omit) }}"
        serole:        "{{ path.serole        | d(omit) }}"
        setype:        "{{ path.setype        | d(omit) }}"
        seuser:        "{{ path.seuser        | d(omit) }}"
        src:           "{{ path.src           | d(omit) }}"
        state:         "{{ path.state         | d(omit) }}"
        unsafe_writes: "{{ path.unsafe_writes | d(omit) }}"
      with_items: "{{ paths }}"
      loop_control:
        loop_var: path
      tags:
        - user
        - file

...