---

- assert:
    that:
      - gnome_settings is sequence

- # name:
  become: yes
  include_tasks: gnome_setting.yml
  with_items: "{{ gnome_settings
                | mass_table_join(gnome_settings_list, 'id')
                | list
               }}"
  loop_control:
    loop_var: gnome_setting
  vars:
    ansible_ssh_pipelining: yes

...