---

- assert:
    that:
      - repos is sequence

- # name:
  include_tasks: repo.yml
  with_items: "{{ repos
                | default_key('id')
                | mass_table_join(repo_list, 'id')
                | list
               }}"
  loop_control:
    loop_var: repo

...