#!/bin/bash

############
# ACCEPT localhost or local network connections
# ----------
iptables -A OUTPUT -m owner --gid-owner ni127 -d 127.0.0.0/8 -j ACCEPT
iptables -A OUTPUT -m owner --gid-owner ni192 -d 127.0.0.0/8 -j ACCEPT
iptables -A OUTPUT -m owner --gid-owner ni192 -d 192.168.0.0/16 -j ACCEPT

############
# REJECT non local connections
# ----------
iptables -A OUTPUT -m owner --gid-owner ni127 -j REJECT
iptables -A OUTPUT -m owner --gid-owner ni192 -j REJECT
