#!/bin/bash

############
# ACCEPT local connections
# ----------
iptables -A OUTPUT -m owner --gid-owner no-internet -d 127.0.0.1/8 -j ACCEPT

############
# REJECT non local connections
# ----------
iptables -A OUTPUT -m owner --gid-owner no-internet -j REJECT

